"""Generate public/frames/cz-prague.svg — the Czechia card background.

Dusk over Prague: Hradčany with St. Vitus on the hill, the sea of red
rooftops with the Týn spires, and the Vltava below with Charles Bridge,
flickering gas lamps (SMIL) and a swan drifting across.
"""
import random

W, H = 400, 600
RIVER = 420
out = []

out.append(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- full-card Prague dusk for the Czechia card: Hradčany and St. Vitus on
       the hill, the city of a hundred spires as a sea of red rooftops, and
       the Vltava with Charles Bridge — lamps flicker, a swan drifts (SMIL).
       Generated by scripts/build-prague.py. -->
  <defs>
    <linearGradient id="czSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#332a5c" stop-opacity="0.96"/>
      <stop offset="0.55" stop-color="#7d5578" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#d08a70" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="czRiver" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#22304e"/>
      <stop offset="1" stop-color="#101a2e"/>
    </linearGradient>
    <filter id="czSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="2.5"/>
    </filter>
  </defs>

  <rect width="{W}" height="250" fill="url(#czSky)"/>
  <g fill="#ffffff">
    <circle cx="52" cy="34" r="1.1" opacity="0.6"/>
    <circle cx="146" cy="22" r="1" opacity="0.5"/>
    <circle cx="238" cy="44" r="1.1" opacity="0.55"/>
    <circle cx="330" cy="28" r="1" opacity="0.5"/>
    <circle cx="86" cy="66" r="1.2" opacity="0.5">
      <animate attributeName="opacity" values="0.2;0.75;0.2" dur="3.6s" repeatCount="indefinite"/>
    </circle>
    <circle cx="296" cy="72" r="1.1" opacity="0.5">
      <animate attributeName="opacity" values="0.2;0.7;0.2" dur="4.4s" begin="1.6s" repeatCount="indefinite"/>
    </circle>
  </g>

  <!-- Hradčany: the castle's long wall and St. Vitus above the hill -->
  <g fill="#2c2545">
    <!-- hill -->
    <path d="M0 320 L0 216 Q90 200 180 212 Q290 226 400 214 L400 320 Z"/>
    <!-- castle wall with towers -->
    <rect x="34" y="196" width="150" height="22"/>
    <rect x="30" y="188" width="12" height="30"/>
    <path d="M28 188 L36 176 L44 188 Z"/>
    <rect x="172" y="188" width="12" height="30"/>
    <path d="M170 188 L178 176 L186 188 Z"/>
    <!-- St. Vitus: two openwork west spires and the great south tower -->
    <path d="M86 196 L92 138 L98 196 Z"/>
    <path d="M104 196 L110 138 L116 196 Z"/>
    <rect x="88" y="168" width="26" height="28"/>
    <rect x="124" y="160" width="16" height="36"/>
    <path d="M122 160 L132 132 L142 160 Z"/>
    <path d="M130.4 128 A2 2 0 1 0 130.4 132 A2.4 2.4 0 1 1 130.4 128 Z" fill="#3a3153"/>
  </g>
  <!-- lit castle windows -->
  <g fill="#e8b04a" opacity="0.8">
    <rect x="52" y="202" width="3" height="5"/>
    <rect x="84" y="203" width="3" height="5"/>
    <rect x="120" y="202" width="3" height="5"/>
    <rect x="152" y="203" width="3" height="5"/>
  </g>
''')

out.append('''  <!-- the Týn church's twin spires and the Powder Tower, rising from
       BEHIND the rooftops — their bodies are hidden by the houses -->
  <g fill="#3a2c40">
    <rect x="118" y="228" width="34" height="56"/>
    <path d="M116 234 L127 186 L138 234 Z"/>
    <path d="M134 234 L145 186 L156 234 Z"/>
    <path d="M122 200 L127 192 L132 200 Z"/>
    <path d="M140 200 L145 192 L150 200 Z"/>
    <rect x="300" y="230" width="18" height="54"/>
    <path d="M298 230 L309 196 L320 230 Z"/>
  </g>
  <g fill="#e8c34a">
    <circle cx="127" cy="185" r="2"/>
    <circle cx="145" cy="185" r="2"/>
    <circle cx="309" cy="195" r="1.8"/>
  </g>''')

# ---- the sea of red rooftops: four rows, hazier and smaller at the back ----
rng = random.Random(77)
rows = [
    # (baseline, min_h, max_h, min_w, max_w, roof_colors, walls, haze_opacity)
    (284, 14, 22, 22, 36, ['#9a5a4a', '#a05f4c', '#93544a'], ['#c4ac94', '#bba184', '#cbb49c'], 0.92),
    (322, 18, 27, 26, 42, ['#a84a38', '#b05541', '#9c4536'], ['#d0b89c', '#c5ab8c', '#d8c2a8'], 1.0),
    (360, 21, 30, 30, 48, ['#a4432f', '#b04a38', '#963c2c'], ['#d8c1a4', '#ccb394', '#dfcab0'], 1.0),
    (398, 24, 33, 34, 54, ['#8f3a28', '#9c4230', '#853424'], ['#cdb598', '#c1a888', '#d5bfa4'], 1.0),
]
for baseline, h_lo, h_hi, w_lo, w_hi, colors, walls, op in rows:
    parts = [f'  <g opacity="{op}">']
    x = -8
    while x < W + 8:
        w = rng.uniform(w_lo, w_hi)
        h = rng.uniform(h_lo, h_hi)
        b = baseline + rng.uniform(-7, 7)  # stagger each house — no flat rows
        c = rng.choice(colors)
        wall = rng.choice(walls)
        kind = rng.random()
        # wall below every roof, down past the next row's baseline
        parts.append(f'    <rect x="{x:.1f}" y="{b:.1f}" width="{w:.1f}" height="60" fill="{wall}"/>')
        if kind < 0.6:  # gable
            parts.append(f'    <path d="M{x - 1.5:.1f} {b:.1f} L{x + w / 2:.1f} {b - h:.1f} L{x + w + 1.5:.1f} {b:.1f} Z" fill="{c}"/>')
        else:  # hipped ridge
            r = w * rng.uniform(0.25, 0.4)
            parts.append(f'    <path d="M{x - 1.5:.1f} {b:.1f} L{x + r:.1f} {b - h:.1f} L{x + w - r:.1f} {b - h:.1f} L{x + w + 1.5:.1f} {b:.1f} Z" fill="{c}"/>')
        if rng.random() < 0.38:
            cx = x + rng.uniform(0.25, 0.7) * w
            parts.append(f'    <rect x="{cx:.1f}" y="{b - h - 6:.1f}" width="4" height="{h * 0.55 + 6:.1f}" fill="{c}"/>')
        if rng.random() < 0.3 and baseline > 300:
            wx = x + w * rng.uniform(0.3, 0.6)
            parts.append(f'    <rect x="{wx:.1f}" y="{b + rng.uniform(6, 14):.1f}" width="3.5" height="6" rx="1.5" fill="#e8b04a" opacity="0.8"/>')
        x += w
    parts.append('  </g>')
    out.append('\n'.join(parts))

# ---- the Vltava and Charles Bridge ----
out.append(f'''
  <rect y="{RIVER}" width="{W}" height="{H - RIVER}" fill="url(#czRiver)"/>

  <!-- Charles Bridge: deck, statues, lamps, arches into the water -->
  <g>
    <rect x="-4" y="428" width="408" height="13" fill="#5f5670"/>
    <rect x="-4" y="428" width="408" height="2.5" fill="#786e8c"/>
    <g fill="none" stroke="#5f5670" stroke-width="6">
      <path d="M28 470 A34 30 0 0 1 96 470"/>
      <path d="M124 470 A34 30 0 0 1 192 470"/>
      <path d="M220 470 A34 30 0 0 1 288 470"/>
      <path d="M316 470 A34 30 0 0 1 384 470"/>
    </g>
    <g fill="#5f5670">
      <rect x="96" y="438" width="28" height="34"/>
      <rect x="192" y="438" width="28" height="34"/>
      <rect x="288" y="438" width="28" height="34"/>
      <rect x="-4" y="438" width="32" height="34"/>
      <rect x="384" y="438" width="20" height="34"/>
    </g>
    <!-- statues along the parapet -->
    <g fill="#332b48">
      <path d="M62 428 L62 414 Q66 408 70 414 L70 428 Z"/>
      <path d="M158 428 L158 412 Q162 406 166 412 L166 428 Z"/>
      <path d="M254 428 L254 414 Q258 408 262 414 L262 428 Z"/>
      <path d="M348 428 L348 412 Q352 406 356 412 L356 428 Z"/>
    </g>
    <!-- gas lamps, each with its own flicker -->
    <g>
      <line x1="110" y1="428" x2="110" y2="412" stroke="#332b48" stroke-width="2"/>
      <circle cx="110" cy="409" r="6" fill="#ffd9a0" opacity="0.3"/>
      <circle cx="110" cy="409" r="2.6" fill="#ffd9a0">
        <animate attributeName="opacity" values="0.8;1;0.85;1;0.8" dur="3.8s" repeatCount="indefinite"/>
      </circle>
      <line x1="206" y1="428" x2="206" y2="412" stroke="#332b48" stroke-width="2"/>
      <circle cx="206" cy="409" r="6" fill="#ffd9a0" opacity="0.3"/>
      <circle cx="206" cy="409" r="2.6" fill="#ffd9a0">
        <animate attributeName="opacity" values="1;0.8;1;0.9;1" dur="4.6s" begin="1.2s" repeatCount="indefinite"/>
      </circle>
      <line x1="302" y1="428" x2="302" y2="412" stroke="#332b48" stroke-width="2"/>
      <circle cx="302" cy="409" r="6" fill="#ffd9a0" opacity="0.3"/>
      <circle cx="302" cy="409" r="2.6" fill="#ffd9a0">
        <animate attributeName="opacity" values="0.85;1;0.8;1;0.85" dur="4.2s" begin="0.6s" repeatCount="indefinite"/>
      </circle>
    </g>
  </g>

  <!-- lamplight smeared down the water -->
  <g fill="#ffd9a0" filter="url(#czSoft)">
    <rect x="106" y="474" width="8" height="42" opacity="0.1"/>
    <rect x="202" y="474" width="8" height="50" opacity="0.11"/>
    <rect x="298" y="474" width="8" height="38" opacity="0.1"/>
  </g>
  <g fill="none" stroke="#8aa4c8" stroke-width="1.5" opacity="0.14">
    <path d="M0 500 Q100 496 200 500 T400 500"/>
    <path d="M0 540 Q100 536 200 540 T400 540"/>
    <path d="M0 576 Q100 572 200 576 T400 576"/>
  </g>

  <!-- a swan drifting downstream -->
  <g>
    <animateTransform attributeName="transform" type="translate"
      values="-30 512; 430 506" dur="90s" repeatCount="indefinite"/>
    <path d="M-9 0 Q0 4.5 9 0 L6 -3 L-7 -3 Z" fill="#f2f2ee"/>
    <path d="M6 -3 Q10 -8 7 -12 Q5 -15 7 -17" fill="none" stroke="#f2f2ee" stroke-width="2.4" stroke-linecap="round"/>
    <path d="M7 -17.5 L11 -16.5 L7.5 -14.8 Z" fill="#e8a94a"/>
    <path d="M-14 2.5 Q0 5.5 14 2.5" fill="none" stroke="#8aa4c8" stroke-width="1" opacity="0.35"/>
  </g>
</svg>''')

open('public/frames/cz-prague.svg', 'w').write('\n'.join(out) + '\n')
print('written public/frames/cz-prague.svg')
