"""Generate public/frames/be-brussels.svg — the Belgium card background.

The Grand-Place on a bright day: gold-trimmed guildhall gables shoulder to
shoulder, the town hall's openwork spire, the silver Atomium rising from
behind the rooflines, striped café awnings and the cobbled square below.
Sky-critical content stays in the y 190-245 band (the card cover-crops the
top ~185 units).
"""
import random

W, H = 400, 600
SQUARE = 460  # where the facades meet the cobbles
out = []

out.append(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- the Grand-Place by day for the Belgium card: guildhall gables with
       gold trim, the town hall spire, the silver Atomium behind the
       rooflines, café awnings on the cobbled square.
       Generated by scripts/build-brussels.py. -->
  <defs>
    <linearGradient id="beSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#4a86c8" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#bcdaee" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="beCobble" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#4a3f33"/>
      <stop offset="1" stop-color="#2b2419"/>
    </linearGradient>
  </defs>

  <rect width="{W}" height="{SQUARE}" fill="url(#beSky)"/>
  <g fill="#f4f8fc" opacity="0.85">
    <ellipse cx="64" cy="204" rx="28" ry="7.5"/>
    <ellipse cx="86" cy="197" rx="17" ry="5.5"/>
    <ellipse cx="330" cy="226" rx="24" ry="7"/>
  </g>

  <!-- the Atomium in stainless steel, rising from behind the guildhalls -->
  <g stroke="#98a2b2" stroke-width="1.6" fill="#98a2b2">
    <line x1="278" y1="344" x2="302" y2="320"/>
    <line x1="302" y1="320" x2="326" y2="344"/>
    <line x1="278" y1="320" x2="326" y2="320"/>
    <line x1="278" y1="344" x2="326" y2="344"/>
    <line x1="302" y1="308" x2="302" y2="356"/>
    <circle cx="302" cy="308" r="4.5"/>
    <circle cx="278" cy="320" r="4.5"/>
    <circle cx="326" cy="320" r="4.5"/>
    <circle cx="302" cy="332" r="5"/>
    <circle cx="278" cy="344" r="4.5"/>
    <circle cx="326" cy="344" r="4.5"/>
    <circle cx="302" cy="356" r="4.5"/>
    <circle cx="303.5" cy="306.5" r="1.4" fill="#ffffff" stroke="none"/>
  </g>

  <!-- distant rooftops closing the square's west side -->
  <g>
    <rect x="-8" y="382" width="34" height="80" fill="#a89a86"/>
    <path d="M-10 382 L9 370 L28 382 Z" fill="#8a7d6a"/>
    <rect x="26" y="392" width="30" height="70" fill="#b0a28c"/>
    <path d="M24 392 L41 378 L58 392 Z" fill="#93866f"/>
    <rect x="56" y="386" width="28" height="76" fill="#a89a86"/>
    <path d="M54 386 L70 372 L86 386 Z" fill="#8a7d6a"/>
    <rect x="84" y="394" width="24" height="68" fill="#b0a28c"/>
    <path d="M82 394 L96 382 L110 394 Z" fill="#93866f"/>
    <g fill="#4a4438" opacity="0.8">
      <rect x="4" y="398" width="4" height="7" rx="1.5"/>
      <rect x="38" y="406" width="4" height="7" rx="1.5"/>
      <rect x="66" y="400" width="4" height="7" rx="1.5"/>
      <rect x="94" y="408" width="4" height="7" rx="1.5"/>
    </g>
  </g>

  <!-- the town hall: gothic body and its openwork spire -->
  <g>
    <rect x="104" y="312" width="44" height="148" fill="#9a8f80"/>
    <rect x="100" y="304" width="52" height="10" fill="#847a6c"/>
    <rect x="118" y="252" width="16" height="60" fill="#9a8f80"/>
    <path d="M118 252 L126 196 L134 252 Z" fill="#847a6c"/>
    <g stroke="#b3a896" stroke-width="1.6">
      <line x1="119" y1="264" x2="133" y2="264"/>
      <line x1="120" y1="240" x2="132" y2="240"/>
      <line x1="122" y1="222" x2="130" y2="222"/>
    </g>
    <circle cx="126" cy="193" r="2.2" fill="#e8c34a"/>
    <g fill="#4a4438" opacity="0.85">
      <rect x="110" y="330" width="5" height="9" rx="2"/>
      <rect x="124" y="330" width="5" height="9" rx="2"/>
      <rect x="138" y="330" width="5" height="9" rx="2"/>
      <rect x="110" y="368" width="5" height="9" rx="2"/>
      <rect x="138" y="368" width="5" height="9" rx="2"/>
      <rect x="110" y="406" width="5" height="9" rx="2"/>
      <rect x="124" y="406" width="5" height="9" rx="2"/>
      <rect x="138" y="406" width="5" height="9" rx="2"/>
    </g>
    <path d="M114 460 L114 442 A12 11 0 0 1 138 442 L138 460 Z" fill="#4a4438"/>
  </g>
''')

# ---- the guildhalls: shoulder to shoulder, shorter, each with a gable ----
rng = random.Random(55)
gables = ['step', 'scroll', 'point', 'scroll', 'step', 'point', 'scroll']
bodies = ['#c4b49e', '#b8a88e', '#cbbca4', '#b0a189']
awnings = ['#c8342a', '#2e7a3c', '#b07d2c']
x = 160
i = 0
parts = ['  <g>']
while x < W + 10:
    w = rng.uniform(40, 54)
    top = rng.uniform(342, 362)
    body = bodies[i % len(bodies)]
    kind = gables[i % len(gables)]
    parts.append(f'    <rect x="{x:.1f}" y="{top:.1f}" width="{w:.1f}" height="{SQUARE - top:.1f}" fill="{body}"/>')
    # party wall line between neighbours instead of a sky gap
    parts.append(f'    <line x1="{x:.1f}" y1="{top + 4:.1f}" x2="{x:.1f}" y2="{SQUARE:.1f}" stroke="#8a7d6a" stroke-width="1.2" opacity="0.7"/>')
    # the gable, gold-trimmed
    if kind == 'step':
        gd = (f'M{x:.1f} {top:.1f} L{x + w * 0.16:.1f} {top:.1f} L{x + w * 0.16:.1f} {top - 10:.1f} '
              f'L{x + w * 0.36:.1f} {top - 10:.1f} L{x + w * 0.36:.1f} {top - 20:.1f} '
              f'L{x + w * 0.64:.1f} {top - 20:.1f} L{x + w * 0.64:.1f} {top - 10:.1f} '
              f'L{x + w * 0.84:.1f} {top - 10:.1f} L{x + w * 0.84:.1f} {top:.1f} L{x + w:.1f} {top:.1f}')
    elif kind == 'scroll':
        gd = (f'M{x:.1f} {top:.1f} Q{x + w * 0.22:.1f} {top - 5:.1f} {x + w * 0.3:.1f} {top - 13:.1f} '
              f'Q{x + w * 0.5:.1f} {top - 28:.1f} {x + w * 0.7:.1f} {top - 13:.1f} '
              f'Q{x + w * 0.78:.1f} {top - 5:.1f} {x + w:.1f} {top:.1f}')
    else:
        gd = (f'M{x:.1f} {top:.1f} L{x + w * 0.5:.1f} {top - 25:.1f} L{x + w:.1f} {top:.1f}')
    parts.append(f'    <path d="{gd} Z" fill="{body}"/>')
    parts.append(f'    <path d="{gd}" fill="none" stroke="#e8c34a" stroke-width="1.8" opacity="0.95"/>')
    parts.append(f'    <circle cx="{x + w / 2:.1f}" cy="{top - (25 if kind == "point" else 20) - 4:.1f}" r="1.8" fill="#e8c34a"/>')
    # windows: three columns of day-dark glass with pale sills
    wy = top + 12
    while wy < SQUARE - 26:
        for col in range(3):
            wx = x + w * (0.18 + 0.28 * col)
            parts.append(f'    <rect x="{wx:.1f}" y="{wy:.1f}" width="6" height="10" rx="1.5" fill="#4a4438" opacity="0.85"/>')
            parts.append(f'    <rect x="{wx - 1:.1f}" y="{wy + 10:.1f}" width="8" height="1.4" fill="#ede4d2"/>')
        wy += 24
    # striped café awning at the base
    aw = awnings[i % len(awnings)]
    parts.append(f'    <rect x="{x + 3:.1f}" y="{SQUARE - 16:.1f}" width="{w - 6:.1f}" height="16" fill="#5a5044"/>')
    parts.append(f'    <rect x="{x + 2:.1f}" y="{SQUARE - 20:.1f}" width="{w - 4:.1f}" height="6" fill="{aw}"/>')
    parts.append(f'    <rect x="{x + 2:.1f}" y="{SQUARE - 15.5:.1f}" width="{w - 4:.1f}" height="1.8" fill="#f2ead8"/>')
    x += w
    i += 1
parts.append('  </g>')
out.append('\n'.join(parts))

# ---- the cobbled square ----
out.append(f'''  <rect y="{SQUARE}" width="{W}" height="{H - SQUARE}" fill="url(#beCobble)"/>''')
parts = ['  <g fill="none" stroke="#5f5244" stroke-width="1.5" opacity="0.55">']
yy = SQUARE + 14
row = 0
while yy < H + 10:
    off = 14 if row % 2 else 0
    xx = -10 + off
    while xx < W + 10:
        r = 14 + row * 2.2
        parts.append(f'    <path d="M{xx:.1f} {yy:.1f} A{r:.1f} {r * 0.42:.1f} 0 0 1 {xx + r * 2:.1f} {yy:.1f}"/>')
        xx += r * 2
    yy += 10 + row * 2.4
    row += 1
parts.append('  </g>')
out.append('\n'.join(parts))
out.append('</svg>')

open('public/frames/be-brussels.svg', 'w').write('\n'.join(out) + '\n')
print('written public/frames/be-brussels.svg')
