import math, random

W, H = 400, 600
WATER = 440          # the Titisee waterline
out = []

def ridge(base_fn, step, tooth_lo, tooth_hi, seed, bottom):
    """Forested ridge: smooth profile with spruce teeth along the crest."""
    rng = random.Random(seed)
    pts = []
    x = -6
    while x <= W + 6:
        y = base_fn(x)
        h = rng.uniform(tooth_lo, tooth_hi)
        pts.append((x, y - h))
        pts.append((x + step / 2, y - rng.uniform(0, tooth_lo * 0.35)))
        x += step
    d = [f"M-6 {bottom}", f"L{pts[0][0]:.1f} {pts[0][1]:.1f}"]
    for px, py in pts[1:]:
        d.append(f"L{px:.1f} {py:.1f}")
    d.append(f"L{W + 6} {bottom} Z")
    return " ".join(d)

def hump(cx, half_w, peak_y, base_y, step, tooth_lo, tooth_hi, seed, bottom):
    """Forested spur: a cosine hump with spruce teeth, used to hide the
    viaduct's ends in hillsides instead of leaving them floating."""
    rng = random.Random(seed)
    def prof(x):
        t = (x - cx) / half_w
        if abs(t) >= 1:
            return base_y
        return base_y - (base_y - peak_y) * (0.5 + 0.5 * math.cos(math.pi * t))
    x_start, x_end = cx - half_w, cx + half_w
    d = [f"M{x_start:.1f} {bottom}"]
    x = x_start
    while x <= x_end:
        y = prof(x)
        d.append(f"L{x:.1f} {y - rng.uniform(tooth_lo, tooth_hi):.1f}")
        d.append(f"L{x + step / 2:.1f} {y - rng.uniform(0, tooth_lo * 0.4):.1f}")
        x += step
    d.append(f"L{x_end:.1f} {bottom} Z")
    return " ".join(d)

far  = ridge(lambda x: 322 - 16 * math.sin(x / 78) - 7 * math.sin(x / 31 + 1.2), 8, 4, 9,  11, H)
mid  = ridge(lambda x: 372 - 20 * math.sin(x / 96 + 2.1) - 8 * math.sin(x / 37), 9, 5, 11, 23, H)
near = ridge(lambda x: 418 - 14 * math.sin(x / 118 + 0.7) - 6 * math.sin(x / 44 + 2.4), 10, 6, 13, 37, WATER)

out.append(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- full-card Schwarzwald for the Germany card: an autumn golden-hour sky
       over forested ridges receding into mist, a Black Forest farmhouse with
       lit windows, a steam train crossing a stone viaduct (SMIL), and the
       Titisee below mirroring the pines. Generated by gen-schwarzwald.py. -->
  <defs>
    <linearGradient id="deSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#575b86" stop-opacity="0.96"/>
      <stop offset="0.46" stop-color="#c2836e" stop-opacity="0.96"/>
      <stop offset="0.8" stop-color="#e8b47e" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#f7e2b4" stop-opacity="0.96"/>
    </linearGradient>
    <radialGradient id="deGlow" cx="0.36" cy="0.98" r="0.62">
      <stop offset="0" stop-color="#ffdca4" stop-opacity="0.42"/>
      <stop offset="1" stop-color="#ffdca4" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="deMid" x1="0" y1="0.55" x2="0" y2="1">
      <stop offset="0" stop-color="#75806c"/>
      <stop offset="1" stop-color="#5c6656"/>
    </linearGradient>
    <linearGradient id="deNear" x1="0" y1="0.72" x2="0" y2="1">
      <stop offset="0" stop-color="#3d4c3a"/>
      <stop offset="1" stop-color="#2b3729"/>
    </linearGradient>
    <linearGradient id="deLake" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#31434b"/>
      <stop offset="0.5" stop-color="#20303a"/>
      <stop offset="1" stop-color="#141f28"/>
    </linearGradient>
    <filter id="deBlur" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="3.5"/>
    </filter>
    <filter id="deBlurSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="2"/>
    </filter>
    <path id="deNearRidge" d="{near}"/>
    <g id="deFarm">
      <!-- walls, then the enormous hipped roof sweeping almost to the ground -->
      <rect x="52" y="422" width="78" height="15" fill="#cdbc9e"/>
      <path d="M36 424 L62 371 L120 371 L146 424 Z" fill="#443a30"/>
      <path d="M62 371 L120 371 L131 393 L51 393 Z" fill="#4f4438"/>
      <path d="M51 393 L131 393 L134 400 L48 400 Z" fill="#3b332a"/>
      <rect x="98" y="360" width="7" height="12" fill="#6b5a48"/>
      <rect x="96.5" y="358" width="10" height="3" fill="#7d6a55"/>
      <g fill="#f2b95c">
        <rect x="60" y="426" width="7" height="8" rx="1"/>
        <rect x="74" y="426" width="7" height="8" rx="1"/>
        <rect x="103" y="426" width="7" height="8" rx="1"/>
        <rect x="117" y="426" width="7" height="8" rx="1"/>
      </g>
      <g fill="#e8a94a" opacity="0.8">
        <rect x="79" y="377" width="6" height="5" rx="1"/>
        <rect x="90" y="377" width="6" height="5" rx="1"/>
      </g>
    </g>
  </defs>

  <rect width="{W}" height="330" fill="url(#deSky)"/>
  <rect width="{W}" height="330" fill="url(#deGlow)"/>

  <!-- far ridge, bleached by haze -->
  <path d="{far}" fill="#95909f"/>
  <rect x="-10" y="316" width="420" height="20" fill="#ffffff" opacity="0.16" filter="url(#deBlur)"/>

  <!-- mid ridge -->
  <path d="{mid}" fill="url(#deMid)"/>''')

# ---- the viaduct: deck, piers, arch rings ----
x0, x1 = 196, 392
pier_w, n_piers = 9, 5
deck_y, pier_bot = 362, 404
piers = [x0 + i * ((x1 - x0 - pier_w) / (n_piers - 1)) for i in range(n_piers)]
out.append('\n  <!-- the viaduct: arch rings show the misty valley through them -->\n  <g>')
out.append(f'    <rect x="{x0 - 3}" y="{deck_y}" width="{x1 - x0 + 6}" height="7" fill="#8d857a"/>')
out.append(f'    <rect x="{x0 - 3}" y="{deck_y + 5}" width="{x1 - x0 + 6}" height="2" fill="#6d6559"/>')
for p in piers:
    out.append(f'    <rect x="{p:.1f}" y="{deck_y + 7}" width="{pier_w}" height="{pier_bot - deck_y - 7}" fill="#7e766b"/>')
out.append('    <g fill="none" stroke="#7e766b" stroke-width="5">')
for a, b in zip(piers, piers[1:]):
    left, right = a + pier_w, b
    r = (right - left) / 2
    out.append(f'      <path d="M{left:.1f} 396 A{r:.1f} {r:.1f} 0 0 1 {right:.1f} 396"/>')
out.append('    </g>\n  </g>')

# ---- steam train crossing the deck ----
spur_l = hump(178, 52, 344, 424, 8, 5, 11, 71, WATER)
spur_r = hump(384, 38, 328, 424, 8, 5, 11, 83, WATER)
out.append(f'''
  <!-- steam train: fades out of the mist at each end so the loop is seamless -->
  <g>
    <animateTransform attributeName="transform" type="translate"
      values="188 0; 356 0" dur="28s" repeatCount="indefinite"/>
    <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.12;0.88;1" dur="28s" repeatCount="indefinite"/>
    <g fill="#c9c2b6" opacity="0.5">
      <circle cx="9" cy="340" r="3.4"><animate attributeName="cy" values="342;326" dur="2.4s" repeatCount="indefinite"/><animate attributeName="r" values="2;6" dur="2.4s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.55;0" dur="2.4s" repeatCount="indefinite"/></circle>
      <circle cx="9" cy="340" r="3.4"><animate attributeName="cy" values="342;326" dur="2.4s" begin="0.8s" repeatCount="indefinite"/><animate attributeName="r" values="2;6" dur="2.4s" begin="0.8s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.55;0" dur="2.4s" begin="0.8s" repeatCount="indefinite"/></circle>
      <circle cx="9" cy="340" r="3.4"><animate attributeName="cy" values="342;326" dur="2.4s" begin="1.6s" repeatCount="indefinite"/><animate attributeName="r" values="2;6" dur="2.4s" begin="1.6s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.55;0" dur="2.4s" begin="1.6s" repeatCount="indefinite"/></circle>
    </g>
    <rect x="4" y="349" width="16" height="9" rx="1.5" fill="#22262b"/>
    <rect x="14" y="344" width="7" height="6" rx="1" fill="#22262b"/>
    <rect x="7" y="343" width="4" height="7" rx="1" fill="#22262b"/>
    <rect x="23" y="350" width="10" height="8" rx="1" fill="#7a2b2b"/>
    <rect x="35" y="350" width="10" height="8" rx="1" fill="#7a2b2b"/>
    <g fill="#c9a86a" opacity="0.85">
      <rect x="25" y="352" width="2.5" height="3"/>
      <rect x="29" y="352" width="2.5" height="3"/>
      <rect x="37" y="352" width="2.5" height="3"/>
      <rect x="41" y="352" width="2.5" height="3"/>
    </g>
    <rect x="4" y="358" width="41" height="2" fill="#1a1d21"/>
  </g>

  <!-- forested spurs: the viaduct runs into the hillsides at both ends -->
  <path d="{spur_l}" fill="#66705e"/>
  <path d="{spur_r}" fill="#66705e"/>

  <rect x="-10" y="392" width="420" height="18" fill="#ffffff" opacity="0.13" filter="url(#deBlur)"/>

  <!-- near ridge and the farmhouse on its shoulder -->
  <use href="#deNearRidge" fill="url(#deNear)"/>
  <use href="#deFarm"/>

  <!-- the Titisee -->
  <rect y="{WATER}" width="{W}" height="{H - WATER}" fill="url(#deLake)"/>
  <!-- mirrored pines and farmhouse, broken up by the water -->
  <g transform="translate(0 {WATER * 2}) scale(1 -1)" opacity="0.36">
    <use href="#deNearRidge" fill="#6a7d62"/>
  </g>
  <g transform="translate(0 {WATER * 2}) scale(1 -1)" opacity="0.22" filter="url(#deBlurSoft)">
    <use href="#deFarm"/>
  </g>
  <!-- the farmhouse's window glow smeared down the water -->
  <g fill="#f2b95c" opacity="0.16" filter="url(#deBlurSoft)">
    <rect x="65" y="{WATER}" width="5" height="46"/>
    <rect x="80" y="{WATER}" width="5" height="38"/>
    <rect x="106" y="{WATER}" width="5" height="42"/>
  </g>
  <!-- ripples and drifting mist on the lake -->
  <g fill="none" stroke="#9fc4d8" stroke-width="1.5" opacity="0.14">
    <path d="M0 {WATER + 26} Q100 {WATER + 22} 200 {WATER + 26} T400 {WATER + 26}"/>
    <path d="M0 {WATER + 58} Q100 {WATER + 54} 200 {WATER + 58} T400 {WATER + 58}"/>
    <path d="M0 {WATER + 96} Q100 {WATER + 92} 200 {WATER + 96} T400 {WATER + 96}"/>
  </g>
  <g filter="url(#deBlur)">
    <rect x="-60" y="{WATER + 14}" width="520" height="13" fill="#ffffff" opacity="0.14">
      <animateTransform attributeName="transform" type="translate" values="-30 0; 30 0; -30 0" dur="46s" repeatCount="indefinite"/>
    </rect>
    <rect x="-60" y="{WATER + 70}" width="520" height="11" fill="#ffffff" opacity="0.1">
      <animateTransform attributeName="transform" type="translate" values="25 0; -25 0; 25 0" dur="58s" repeatCount="indefinite"/>
    </rect>
  </g>
''')

# ---- foreground: the shore we stand on, framed by dark spruces ----
def spruce(cx, base, top, half, tiers, fill):
    """Layered spruce silhouette."""
    parts = [f'    <rect x="{cx - 2.2:.1f}" y="{base - 8:.1f}" width="4.4" height="9" fill="{fill}"/>']
    span = base - top
    for i in range(tiers):
        t = i / tiers
        y_top = top + span * t * 0.62
        y_bot = top + span * (t * 0.62 + 0.42)
        w = half * (0.34 + 0.66 * (t + 0.32) / 1.32)
        parts.append(
            f'    <path d="M{cx:.1f} {y_top:.1f} L{cx + w:.1f} {y_bot:.1f} L{cx - w:.1f} {y_bot:.1f} Z" fill="{fill}"/>'
        )
    return "\n".join(parts)

out.append(f'  <path d="M0 {H} L0 574 Q120 566 210 572 Q320 578 400 570 L400 {H} Z" fill="#0f1a13"/>')
out.append('  <!-- spruces at the shore, framing the card -->')
out.append(spruce(14, 582, 404, 30, 4, '#16241a'))
out.append(spruce(46, 578, 452, 22, 4, '#132018'))
out.append(spruce(378, 580, 420, 27, 4, '#16241a'))
out.append(spruce(350, 576, 470, 19, 3, '#132018'))
out.append('</svg>')

open('/Users/milanalbertz/Desktop/Projects/MilanAlbertzWebsite/public/frames/de-schwarzwald.svg', 'w').write("\n".join(out) + "\n")
print('written', len("\n".join(out)), 'bytes')
