"""Generate the three China place backgrounds:

  cn-hongkong.svg  — Victoria Harbour at night: the Peak, a neon skyline,
                     and a red-sailed junk crossing the black water (SMIL)
  cn-macau.svg     — dusk on the Ruins of St. Paul's, pastel Portuguese
                     houses, the Grand Lisboa glowing behind
  cn-china.svg     — the country default: the Great Wall snaking over dusk
                     mountains, a pagoda among the pines below

Selecting a place crossfades from the country scene to its own.
"""
import random

W, H = 400, 600


# --------------------------------------------------------------- Hong Kong
def hongkong():
    rng = random.Random(88)
    out = [f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- Victoria Harbour at night for the China card: the Peak behind a neon
       skyline, reflections smeared into the harbour, and a red-sailed junk
       crossing (SMIL). Generated by scripts/build-china.py. -->
  <defs>
    <linearGradient id="hkSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#0d1430" stop-opacity="0.97"/>
      <stop offset="1" stop-color="#233156" stop-opacity="0.97"/>
    </linearGradient>
    <linearGradient id="hkSea" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#101a36"/>
      <stop offset="1" stop-color="#080e20"/>
    </linearGradient>
    <filter id="hkSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="2.5"/>
    </filter>
  </defs>

  <rect width="{W}" height="410" fill="url(#hkSky)"/>
  <g fill="#ffffff">
    <circle cx="44" cy="40" r="1.1" opacity="0.55"/>
    <circle cx="150" cy="26" r="1" opacity="0.45"/>
    <circle cx="252" cy="48" r="1.1" opacity="0.5"/>
    <circle cx="342" cy="30" r="1" opacity="0.45"/>
    <circle cx="90" cy="74" r="1.1" opacity="0.45">
      <animate attributeName="opacity" values="0.2;0.7;0.2" dur="4.2s" repeatCount="indefinite"/>
    </circle>
  </g>

  <!-- the Peak, with the Peak Tower's light -->
  <path d="M0 268 L46 210 L108 172 L178 150 L252 176 L318 214 L400 252 L400 410 L0 410 Z" fill="#141b38"/>
  <circle cx="178" cy="152" r="1.8" fill="#ffd98a" opacity="0.9"/>
''']
    # back row of hazy towers
    parts = ['  <g fill="#1e2a52">']
    x = -6
    while x < W:
        w = rng.uniform(20, 34)
        h = rng.uniform(70, 150)
        parts.append(f'    <rect x="{x:.1f}" y="{400 - h:.1f}" width="{w:.1f}" height="{h + 12:.1f}"/>')
        x += w + rng.uniform(2, 9)
    parts.append('  </g>')
    out.append('\n'.join(parts))

    # front row with window grids and neon edges
    neon = ['#ff5fa2', '#4ae0e8', '#ffd23f', '#7a6cff']
    parts = ['  <g>']
    refl = []
    x = -4
    while x < W:
        w = rng.uniform(26, 44)
        h = rng.uniform(110, 210)
        top = 404 - h
        parts.append(f'    <rect x="{x:.1f}" y="{top:.1f}" width="{w:.1f}" height="{h:.1f}" fill="#232f5e"/>')
        # lit windows
        wins = []
        wy = top + 6
        while wy < 396:
            wx = x + 3.5
            while wx < x + w - 4:
                if rng.random() < 0.42:
                    wins.append(f'      <rect x="{wx:.1f}" y="{wy:.1f}" width="2.6" height="3.4"/>')
                wx += 5.5
            wy += 8
        parts.append('    <g fill="#ffd98a" opacity="0.85">')
        parts.extend(wins)
        parts.append('    </g>')
        # occasional neon edge + its reflection
        if rng.random() < 0.55:
            c = rng.choice(neon)
            side = x + 1 if rng.random() < 0.5 else x + w - 2.4
            parts.append(f'    <rect x="{side:.1f}" y="{top:.1f}" width="1.8" height="{h:.1f}" fill="{c}" opacity="0.9"/>')
            refl.append((side, c))
        x += w + rng.uniform(3, 10)
    parts.append('  </g>')
    out.append('\n'.join(parts))

    # landmarks: Bank of China crosshatch + IFC crown
    out.append('''  <!-- Bank of China's lattice and Two IFC -->
  <g>
    <path d="M96 404 L96 226 L122 202 L122 404 Z" fill="#28376a"/>
    <g stroke="#5a6ea8" stroke-width="1.4" opacity="0.85">
      <path d="M96 260 L122 236 M96 300 L122 276 M96 340 L122 316 M96 380 L122 356"/>
      <path d="M96 226 L122 250 M96 266 L122 290 M96 306 L122 330 M96 346 L122 370"/>
    </g>
    <rect x="106" y="188" width="2" height="16" fill="#5a6ea8"/>
    <path d="M262 404 L262 196 L272 178 L282 196 L282 404 Z" fill="#2b3a70"/>
    <g fill="#ffd98a" opacity="0.8">
      <rect x="265" y="210" width="2.4" height="3.2"/><rect x="271" y="224" width="2.4" height="3.2"/>
      <rect x="276" y="204" width="2.4" height="3.2"/><rect x="266" y="252" width="2.4" height="3.2"/>
      <rect x="273" y="266" width="2.4" height="3.2"/><rect x="276" y="290" width="2.4" height="3.2"/>
      <rect x="266" y="308" width="2.4" height="3.2"/><rect x="272" y="330" width="2.4" height="3.2"/>
    </g>
  </g>
''')

    # the harbour with reflections
    out.append(f'  <rect y="404" width="{W}" height="{H - 404}" fill="url(#hkSea)"/>')
    parts = ['  <g filter="url(#hkSoft)">']
    for side, c in refl[:7]:
        parts.append(f'    <rect x="{side - 2:.1f}" y="408" width="5" height="{rng.uniform(34, 70):.1f}" fill="{c}" opacity="0.16"/>')
    for _ in range(9):
        rx = rng.uniform(10, 380)
        parts.append(f'    <rect x="{rx:.1f}" y="408" width="4" height="{rng.uniform(20, 44):.1f}" fill="#ffd98a" opacity="0.1"/>')
    parts.append('  </g>')
    out.append('\n'.join(parts))
    out.append('''  <g fill="none" stroke="#3a4a78" stroke-width="1.5" opacity="0.25">
    <path d="M0 452 Q100 448 200 452 T400 452"/>
    <path d="M0 500 Q100 496 200 500 T400 500"/>
    <path d="M0 548 Q100 544 200 548 T400 548"/>
  </g>

  <!-- the junk, red battened sails glowing against the city -->
  <g>
    <animateTransform attributeName="transform" type="translate"
      values="-50 466; 450 460" dur="70s" repeatCount="indefinite"/>
    <path d="M-20 6 Q0 12 20 6 L15 0 L-16 0 Z" fill="#241a20"/>
    <path d="M-2 0 C-14 -6 -16 -22 -8 -34 C-2 -26 -2 -12 -2 0 Z" fill="#c8342a"/>
    <path d="M2 0 C0 -14 4 -30 14 -38 C18 -24 12 -8 8 0 Z" fill="#d84434"/>
    <g stroke="#8f1f18" stroke-width="1" opacity="0.8">
      <path d="M-11 -10 L-2 -8 M-13 -18 L-3 -16 M-12 -26 L-4 -24"/>
      <path d="M3 -12 L10 -14 M2 -22 L11 -25 M4 -30 L13 -33"/>
    </g>
    <circle cx="0" cy="-40" r="1.6" fill="#ffd98a">
      <animate attributeName="opacity" values="0.7;1;0.7" dur="3s" repeatCount="indefinite"/>
    </circle>
  </g>
</svg>''')
    return '\n'.join(out)


# ------------------------------------------------------------------ Macau
def macau():
    rng = random.Random(99)
    pastels = ['#b8d8c8', '#e8d08a', '#e0aab4', '#c9c4e0', '#e8c49a']
    houses = ['  <g>']
    x = -6
    while x < W + 6:
        w = rng.uniform(34, 52)
        hh = rng.uniform(46, 66)
        c = rng.choice(pastels)
        houses.append(f'    <rect x="{x:.1f}" y="{452 - hh:.1f}" width="{w:.1f}" height="{hh:.1f}" fill="{c}"/>')
        houses.append(f'    <rect x="{x:.1f}" y="{452 - hh:.1f}" width="{w:.1f}" height="5" fill="#8a4f3a"/>')
        wx = x + 6
        while wx < x + w - 8:
            houses.append(f'    <rect x="{wx:.1f}" y="{452 - hh + 12:.1f}" width="6" height="10" rx="2" fill="#4a4238" opacity="0.75"/>')
            if rng.random() < 0.5:
                houses.append(f'    <rect x="{wx - 1.2:.1f}" y="{452 - hh + 10.5:.1f}" width="8.4" height="2" fill="#f4f0e6" opacity="0.9"/>')
            wx += 12
        x += w
    houses.append('  </g>')
    houses_svg = '\n'.join(houses)

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- Macau at dusk for the China card: the Ruins of St. Paul's on their
       hill, pastel Portuguese houses, the Grand Lisboa glowing behind, and
       a whisper of calçada waves along the bottom.
       Generated by scripts/build-china.py. -->
  <defs>
    <linearGradient id="moSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2e2a5c" stop-opacity="0.96"/>
      <stop offset="0.6" stop-color="#8a5470" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#d08a68" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="moGround" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1e2440"/>
      <stop offset="1" stop-color="#131830"/>
    </linearGradient>
  </defs>

  <rect width="{W}" height="452" fill="url(#moSky)"/>
  <g fill="#ffffff">
    <circle cx="60" cy="38" r="1.1" opacity="0.5"/>
    <circle cx="188" cy="26" r="1" opacity="0.45"/>
    <circle cx="330" cy="44" r="1.1" opacity="0.5"/>
  </g>

  <!-- the Grand Lisboa's lotus blade, glowing -->
  <g>
    <path d="M296 452 C288 380 292 300 316 236 C340 300 344 380 336 452 Z" fill="#40365c"/>
    <path d="M300 440 C294 380 298 310 316 252 C334 310 338 380 332 440 Z" fill="none" stroke="#e8c34a" stroke-width="1.6" opacity="0.75">
      <animate attributeName="opacity" values="0.4;0.75;0.4" dur="5s" repeatCount="indefinite"/>
    </path>
    <g stroke="#c9a227" stroke-width="0.9" opacity="0.5">
      <path d="M306 430 C302 370 306 320 316 268"/>
      <path d="M326 430 C330 370 326 320 316 268"/>
    </g>
    <path d="M308 244 L316 222 L324 244 Z" fill="#e8c34a" opacity="0.85"/>
    <ellipse cx="316" cy="452" rx="34" ry="10" fill="#2e2745"/>
  </g>

  <!-- the Ruins of St. Paul's: the wide, FLAT façade that outlived its
       church — squat tiers, columned, dusk showing through the openings -->
  <g>
    <path d="M84 452 L84 356 L220 356 L220 452 Z" fill="#4a4258"/>
    <path d="M98 356 L98 314 L206 314 L206 356 Z" fill="#453d52"/>
    <path d="M114 314 L114 276 L190 276 L190 314 Z" fill="#4a4258"/>
    <path d="M110 276 L152 244 L194 276 Z" fill="#453d52"/>
    <path d="M150 249 L154 249 L154 238 L158 238 L158 235 L154 235 L154 231 L150 231 L150 235 L146 235 L146 238 L150 238 Z" fill="#4a4258"/>
    <!-- openings, holding the dusk behind them -->
    <g fill="#8a5f7e">
      <path d="M138 452 L138 420 A14 12 0 0 1 166 420 L166 452 Z"/>
      <path d="M100 452 L100 426 A9 8 0 0 1 118 426 L118 452 Z"/>
      <path d="M186 452 L186 426 A9 8 0 0 1 204 426 L204 452 Z"/>
      <rect x="106" y="376" width="15" height="22" rx="7"/>
      <rect x="144" y="376" width="15" height="22" rx="7"/>
      <rect x="182" y="376" width="15" height="22" rx="7"/>
      <rect x="112" y="324" width="13" height="19" rx="6"/>
      <rect x="145" y="324" width="13" height="19" rx="6"/>
      <rect x="178" y="324" width="13" height="19" rx="6"/>
      <rect x="134" y="284" width="11" height="17" rx="5"/>
      <rect x="158" y="284" width="11" height="17" rx="5"/>
    </g>
    <g stroke="#5c5268" stroke-width="2.6">
      <line x1="80" y1="356" x2="224" y2="356"/>
      <line x1="94" y1="314" x2="210" y2="314"/>
      <line x1="110" y1="276" x2="194" y2="276"/>
    </g>
    <!-- columns on the lower tiers -->
    <g fill="#564c64">
      <rect x="88" y="362" width="5" height="90"/>
      <rect x="126" y="362" width="5" height="90"/>
      <rect x="164" y="362" width="5" height="90"/>
      <rect x="202" y="362" width="5" height="90"/>
      <rect x="103" y="318" width="4" height="38"/>
      <rect x="136" y="318" width="4" height="38"/>
      <rect x="168" y="318" width="4" height="38"/>
      <rect x="198" y="318" width="4" height="38"/>
    </g>
  </g>

{houses_svg}

  <!-- the stair-plaza with its calçada waves -->
  <rect y="452" width="{W}" height="{H - 452}" fill="url(#moGround)"/>
  <g fill="none" stroke="#d8cfae" stroke-width="4" opacity="0.16">
    <path d="M-12 492 Q18 470 48 492 T108 492 T168 492 T228 492 T288 492 T348 492 T408 492"/>
    <path d="M-12 548 Q18 526 48 548 T108 548 T168 548 T228 548 T288 548 T348 548 T408 548"/>
  </g>
</svg>'''


# ------------------------------------------------------------------ China
def china():
    """The country default: Great Wall over daylight ridges, temples below."""
    import math
    ridge = [(0, 400), (48, 368), (96, 336), (150, 306), (204, 290),
             (258, 312), (310, 344), (360, 372), (400, 388)]

    out = [f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- the China card's country scene, in daylight: the Great Wall riding
       the crest of a green mountain, a red pagoda and shrine below, the
       loong's shadow crossing the sky. Mist drifts via SMIL.
       Generated by scripts/build-china.py. -->
  <defs>
    <linearGradient id="gwSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#3d74c0" stop-opacity="0.96"/>
      <stop offset="0.65" stop-color="#7fa9d8" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#c2d9ea" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="gwValley" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2c4230"/>
      <stop offset="1" stop-color="#182a1c"/>
    </linearGradient>
    <filter id="gwSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="3"/>
    </filter>
  </defs>

  <rect width="{W}" height="470" fill="url(#gwSky)"/>
  <!-- morning sun and slow clouds — kept low: the card's cover-crop
       removes roughly the top 185 units on real aspect ratios -->
  <circle cx="322" cy="204" r="24" fill="#fff3c4" opacity="0.35"/>
  <circle cx="322" cy="204" r="13" fill="#fff3c4"/>
  <g fill="#f4f8fc" opacity="0.85">
    <ellipse cx="66" cy="206" rx="30" ry="8"/>
    <ellipse cx="88" cy="199" rx="19" ry="6"/>
    <ellipse cx="196" cy="192" rx="24" ry="7"/>
    <ellipse cx="380" cy="234" rx="24" ry="7"/>
  </g>
  <!-- distant birds -->
  <g stroke="#2c3a52" stroke-width="1.6" fill="none" stroke-linecap="round">
    <path d="M138 226 Q142 222 146 226 M142 224 Q146 220 150 224"/>
    <path d="M164 210 Q168 206 172 210"/>
  </g>

  <!-- the loong: a distant shadow riding the wind (SMIL) -->
  <g fill="#263349" stroke="#263349" opacity="0.82">
    <animateTransform attributeName="transform" type="translate" values="-70 206; 545 218" dur="50s" repeatCount="indefinite"/>
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0; 0 9; 0 0" dur="6s" repeatCount="indefinite" additive="sum"/>
      <path d="M0 6 C-6 0 -12 2 -16 -2 C-10 8 -14 12 -18 14 C-8 14 -4 12 0 6 Z" stroke="none"/>
      <path d="M0 6 C18 -8 40 -8 58 6 C76 20 98 20 116 6" fill="none" stroke-width="8" stroke-linecap="round"/>
      <g stroke="none">
        <path d="M13.9 -2.6 L17 -9.6 L20.4 -2.2 Z"/>
        <path d="M27 -5.5 L30.4 -12.6 L33.6 -5.1 Z"/>
        <path d="M42 -2.8 L45.4 -9.4 L48.4 -2.1 Z"/>
        <path d="M83 13.4 L86.2 7 L89.3 13.8 Z"/>
      </g>
      <g stroke-width="2" fill="none" stroke-linecap="round">
        <path d="M24 -2 L20 8 M20 8 L16.6 10 M20 8 L22.4 11"/>
        <path d="M48 3 L45 10 M45 10 L41.6 12 M45 10 L47.4 13"/>
        <path d="M72 16 L69 23 M69 23 L65.6 25 M69 23 L71.4 26"/>
        <path d="M98 17 L95 24 M95 24 L91.6 26 M95 24 L97.4 27"/>
      </g>
      <path d="M116 6 C120 -2 132 -4 140 0 C144 2 144 6 141 8 C134 12 122 12 116 6 Z" stroke="none"/>
      <g stroke-width="2" stroke-linecap="round" fill="none">
        <path d="M126 -1.4 L120 -9"/>
        <path d="M131 -2.6 L127 -10.6"/>
      </g>
      <g stroke-width="1.3" fill="none" stroke-linecap="round">
        <path d="M140 2 C148 0 152 -4 154 -8"/>
        <path d="M141 6 C150 6 154 10 155 14"/>
      </g>
    </g>
  </g>

  <!-- far ridges, dissolving into haze -->
  <path d="M0 292 L60 258 L130 276 L210 246 L290 272 L352 252 L400 268 L400 505 L0 505 Z" fill="#7a9ab0" opacity="0.7"/>
  <path d="M0 330 L80 296 L160 318 L250 288 L330 314 L400 300 L400 505 L0 505 Z" fill="#5d86a0" opacity="0.85"/>
''']

    # the wall's mountain, then the wall riding its crest
    ridge_d = 'M' + ' L'.join(f'{x} {y}' for x, y in ridge) + f' L{W} 505 L0 505 Z'
    out.append(f'  <path d="{ridge_d}" fill="#587a52"/>')

    band = ['  <g>']
    for (x1, y1), (x2, y2) in zip(ridge, ridge[1:]):
        band.append(f'    <path d="M{x1} {y1} L{x2} {y2} L{x2} {y2 + 9} L{x1} {y1 + 9} Z" fill="#b3a284"/>')
        band.append(f'    <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#d9caa6" stroke-width="1.6"/>')
        seg = math.hypot(x2 - x1, y2 - y1)
        n = int(seg // 10)
        for k in range(1, n + 1):
            t = k / (n + 1)
            cx = x1 + (x2 - x1) * t
            cy = y1 + (y2 - y1) * t
            band.append(f'    <rect x="{cx - 1.3:.1f}" y="{cy - 3.4:.1f}" width="2.6" height="3.4" fill="#c9baa0"/>')
    band.append('  </g>')
    out.append('\n'.join(band))

    # watchtowers at three crest points
    towers = ['  <g>']
    for i in (2, 4, 6):
        x, y = ridge[i]
        towers.append(f'    <rect x="{x - 9}" y="{y - 22}" width="18" height="26" fill="#a89878"/>')
        towers.append(f'    <rect x="{x - 11.5}" y="{y - 27}" width="23" height="5.5" fill="#6a5a44"/>')
        towers.append(f'    <rect x="{x - 2.2}" y="{y - 16}" width="4.4" height="6" rx="2" fill="#4a3f30"/>')
    towers.append('  </g>')
    out.append('\n'.join(towers))

    # near dark ridge
    out.append(f'  <path d="M0 480 L70 448 L150 468 L240 442 L320 466 L400 452 L400 600 L0 600 Z" fill="#3e5a3c"/>')

    # the valley: fog and the temples
    out.append(f'''  <rect y="490" width="{W}" height="{H - 490}" fill="url(#gwValley)"/>
  <g filter="url(#gwSoft)">
    <rect x="-60" y="472" width="520" height="14" fill="#ffffff" opacity="0.14">
      <animateTransform attributeName="transform" type="translate" values="-24 0; 24 0; -24 0" dur="44s" repeatCount="indefinite"/>
    </rect>
    <rect x="-60" y="520" width="520" height="12" fill="#ffffff" opacity="0.1">
      <animateTransform attributeName="transform" type="translate" values="20 0; -20 0; 20 0" dur="56s" repeatCount="indefinite"/>
    </rect>
  </g>

  <!-- the little shrine on the left shoulder -->
  <g>
    <rect x="66" y="444" width="42" height="4" fill="#7a150e"/>
    <rect x="70" y="448" width="34" height="22" fill="#ede0c8"/>
    <rect x="68.5" y="448" width="4" height="22" fill="#8f1f18"/>
    <rect x="101.5" y="448" width="4" height="22" fill="#8f1f18"/>
    <path d="M83 470 L83 461 A4 4 0 0 1 91 461 L91 470 Z" fill="#5a3a2a"/>
    <path d="M52 440 Q72 434 80 428 L94 428 Q102 434 122 440 Q108 446 87 446 Q66 446 52 440 Z" fill="#a8281e"/>
    <path d="M52 440 Q66 446 87 446 Q108 446 122 440" fill="none" stroke="#7a150e" stroke-width="1.5"/>
    <circle cx="87" cy="425.5" r="1.8" fill="#e8c34a"/>
  </g>

  <!-- the pagoda: ONE tower — broad base, storeys tucked into the roofs
       below them, a quiet finial. Shifted right, clear of the Wall -->
  <g transform="translate(15 0)">
    <!-- first storey -->
    <rect x="286" y="470" width="50" height="4.5" fill="#7a150e"/>
    <rect x="289" y="474" width="44" height="26" fill="#ede0c8"/>
    <rect x="287.5" y="474" width="4.5" height="26" fill="#8f1f18"/>
    <rect x="330" y="474" width="4.5" height="26" fill="#8f1f18"/>
    <path d="M305 500 L305 489 A6 6 0 0 1 317 489 L317 500 Z" fill="#5a3a2a"/>
    <rect x="294" y="479" width="5" height="8" rx="1.5" fill="#5a3a2a"/>
    <rect x="323" y="479" width="5" height="8" rx="1.5" fill="#5a3a2a"/>
    <path d="M262 466 Q290 459 302 448 L320 448 Q332 459 360 466 Q344 473 311 473 Q278 473 262 466 Z" fill="#a8281e"/>
    <path d="M262 466 Q278 473 311 473 Q344 473 360 466" fill="none" stroke="#7a150e" stroke-width="1.6"/>
    <!-- second storey, its base tucked into the roof below -->
    <rect x="295" y="432" width="32" height="26" fill="#ede0c8"/>
    <rect x="293.8" y="432" width="4" height="26" fill="#8f1f18"/>
    <rect x="324.2" y="432" width="4" height="26" fill="#8f1f18"/>
    <rect x="292" y="428" width="38" height="4.5" fill="#7a150e"/>
    <rect x="308" y="438" width="6" height="8.5" rx="1.5" fill="#5a3a2a"/>
    <path d="M274 424 Q297 418 304 408 L318 408 Q325 418 348 424 Q334 430 311 430 Q288 430 274 424 Z" fill="#a8281e"/>
    <path d="M274 424 Q288 430 311 430 Q334 430 348 424" fill="none" stroke="#7a150e" stroke-width="1.5"/>
    <!-- third storey, tucked into the roof below -->
    <rect x="300" y="388" width="22" height="26" fill="#ede0c8"/>
    <rect x="299" y="388" width="3.4" height="26" fill="#8f1f18"/>
    <rect x="319.6" y="388" width="3.4" height="26" fill="#8f1f18"/>
    <rect x="297" y="384" width="28" height="4" fill="#7a150e"/>
    <rect x="308.5" y="392" width="5" height="7" rx="1.5" fill="#5a3a2a"/>
    <path d="M284 380 Q302 375 307 366 L315 366 Q320 375 338 380 Q327 385.5 311 385.5 Q295 385.5 284 380 Z" fill="#a8281e"/>
    <path d="M284 380 Q295 385.5 311 385.5 Q327 385.5 338 380" fill="none" stroke="#7a150e" stroke-width="1.4"/>
    <!-- quiet finial: short pole, one ring, the gold ball -->
    <rect x="309.9" y="354" width="2.2" height="12" fill="#8f1f18"/>
    <rect x="307.5" y="359" width="7" height="1.8" rx="0.9" fill="#7a150e"/>
    <circle cx="311" cy="351.5" r="2.6" fill="#e8c34a"/>
  </g>

  <!-- pines, canopies like held-out sleeves -->
  <g fill="#22361f">
    <path d="M60 600 C62 576 56 556 62 536" stroke="#22361f" stroke-width="4" fill="none"/>
    <ellipse cx="62" cy="534" rx="24" ry="7"/>
    <ellipse cx="50" cy="548" rx="17" ry="5.5"/>
    <ellipse cx="74" cy="552" rx="14" ry="5"/>
    <path d="M128 600 C126 582 132 568 128 554" stroke="#22361f" stroke-width="3.4" fill="none"/>
    <ellipse cx="128" cy="552" rx="18" ry="5.5"/>
    <ellipse cx="140" cy="563" rx="12" ry="4.5"/>
    <path d="M226 600 C228 586 222 576 226 566" stroke="#22361f" stroke-width="3" fill="none"/>
    <ellipse cx="226" cy="564" rx="15" ry="5"/>
  </g>
</svg>''')
    return '\n'.join(out)


for name, fn in [('cn-hongkong', hongkong), ('cn-macau', macau), ('cn-china', china)]:
    path = f'public/frames/{name}.svg'
    open(path, 'w').write(fn() + '\n')
    print('written', path)
