"""Generate public/frames/nl-amsterdam.svg — the Netherlands card background.

Golden hour on an Amsterdam gracht: tall narrow canal houses (bell, neck,
step and spout gables, hoisting beams, a gentle lean here and there),
bikes and tulips along the quay, a houseboat moored, facades reflected in
the dark green water, and a rondvaart boat gliding through (SMIL).
Sky-critical content stays in the y 190-245 band (cover-crop safe).
"""
import random

W, H = 400, 600
QUAY = 432      # facades end, quay begins
WATER = 458     # quay edge meets the canal
rng = random.Random(17)

out = [f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- golden hour on the gracht for the Netherlands card: leaning canal
       houses with their gables and hoisting beams, bikes and tulips on the
       quay, reflections in the water, a rondvaart gliding by (SMIL).
       Generated by scripts/build-amsterdam.py. -->
  <defs>
    <linearGradient id="nlSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#4a7ac0" stop-opacity="0.96"/>
      <stop offset="0.6" stop-color="#a8c4e0" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#f0d8a8" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="nlWater" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#23362e"/>
      <stop offset="1" stop-color="#121e1a"/>
    </linearGradient>
    <filter id="nlSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="2.5"/>
    </filter>
  </defs>

  <rect width="{W}" height="{QUAY}" fill="url(#nlSky)"/>
  <g fill="#f4f8fc" opacity="0.85">
    <ellipse cx="70" cy="206" rx="28" ry="7.5"/>
    <ellipse cx="92" cy="199" rx="17" ry="5.5"/>
    <ellipse cx="312" cy="224" rx="24" ry="7"/>
  </g>
''']

# ---- the canal houses ----
bricks = ['#8a4a34', '#6a3a2a', '#9a5a3c', '#413c46', '#7a4430', '#59544e']
gable_kinds = ['bell', 'neck', 'step', 'spout', 'bell', 'neck']
facades = []   # remember (x, w, brick) for the reflections
parts = ['  <g>']
x = -4
i = 0
while x < W + 4:
    w = rng.uniform(36, 48)
    top = rng.uniform(258, 288)
    brick = bricks[i % len(bricks)]
    kind = gable_kinds[i % len(gable_kinds)]
    lean = rng.uniform(-1.4, 1.4) if rng.random() < 0.45 else 0
    facades.append((x, w, brick))
    g_open = f'    <g transform="rotate({lean:.1f} {x + w / 2:.1f} {QUAY})">' if lean else '    <g>'
    parts.append(g_open)
    parts.append(f'      <rect x="{x:.1f}" y="{top:.1f}" width="{w:.1f}" height="{QUAY - top:.1f}" fill="{brick}"/>')
    parts.append(f'      <line x1="{x:.1f}" y1="{top + 6:.1f}" x2="{x:.1f}" y2="{QUAY}" stroke="#2e2620" stroke-width="1" opacity="0.5"/>')
    cx = x + w / 2
    # the gable
    if kind == 'bell':
        gd = (f'M{x:.1f} {top:.1f} C{x + w * 0.12:.1f} {top - 4:.1f} {x + w * 0.3:.1f} {top - 6:.1f} {cx - 5:.1f} {top - 28:.1f} '
              f'L{cx - 5:.1f} {top - 36:.1f} L{cx + 5:.1f} {top - 36:.1f} L{cx + 5:.1f} {top - 28:.1f} '
              f'C{x + w * 0.7:.1f} {top - 6:.1f} {x + w * 0.88:.1f} {top - 4:.1f} {x + w:.1f} {top:.1f}')
    elif kind == 'neck':
        gd = (f'M{x:.1f} {top:.1f} L{cx - 7:.1f} {top:.1f} L{cx - 8:.1f} {top - 30:.1f} '
              f'L{cx + 8:.1f} {top - 30:.1f} L{cx + 7:.1f} {top:.1f} L{x + w:.1f} {top:.1f}')
    elif kind == 'step':
        gd = (f'M{x:.1f} {top:.1f} L{x + w * 0.2:.1f} {top:.1f} L{x + w * 0.2:.1f} {top - 13:.1f} '
              f'L{x + w * 0.38:.1f} {top - 13:.1f} L{x + w * 0.38:.1f} {top - 26:.1f} '
              f'L{x + w * 0.62:.1f} {top - 26:.1f} L{x + w * 0.62:.1f} {top - 13:.1f} '
              f'L{x + w * 0.8:.1f} {top - 13:.1f} L{x + w * 0.8:.1f} {top:.1f} L{x + w:.1f} {top:.1f}')
    else:  # spout
        gd = (f'M{x:.1f} {top:.1f} L{cx - 10:.1f} {top - 22:.1f} L{cx - 10:.1f} {top - 30:.1f} '
              f'L{cx + 10:.1f} {top - 30:.1f} L{cx + 10:.1f} {top - 22:.1f} L{x + w:.1f} {top:.1f}')
    parts.append(f'      <path d="{gd} Z" fill="{brick}"/>')
    parts.append(f'      <path d="{gd}" fill="none" stroke="#ece4d2" stroke-width="2" opacity="0.92"/>')
    # hoisting beam: its end-on knob at the peak, hook hanging beneath
    beam_y = top - {'bell': 34, 'neck': 28, 'step': 24, 'spout': 28}[kind]
    parts.append(f'      <rect x="{cx - 2:.1f}" y="{beam_y:.1f}" width="4" height="3.4" rx="1" fill="#3a2f24"/>')
    parts.append(f'      <line x1="{cx:.1f}" y1="{beam_y + 3.4:.1f}" x2="{cx:.1f}" y2="{beam_y + 9:.1f}" stroke="#3a2f24" stroke-width="1.2"/>')
    parts.append(f'      <path d="M{cx:.1f} {beam_y + 9:.1f} Q{cx - 2.4:.1f} {beam_y + 11.5:.1f} {cx - 1:.1f} {beam_y + 12.5:.1f}" fill="none" stroke="#3a2f24" stroke-width="1.2"/>')
    # windows: two columns of tall white-framed sashes
    wy = top + 12
    while wy < QUAY - 30:
        for col in (0.26, 0.62):
            wx = x + w * col
            parts.append(f'      <rect x="{wx - 1.4:.1f}" y="{wy - 1.4:.1f}" width="10.8" height="16.8" rx="1" fill="#ece4d2"/>')
            parts.append(f'      <rect x="{wx:.1f}" y="{wy:.1f}" width="8" height="14" fill="#3a3630"/>')
            parts.append(f'      <line x1="{wx:.1f}" y1="{wy + 7:.1f}" x2="{wx + 8:.1f}" y2="{wy + 7:.1f}" stroke="#ece4d2" stroke-width="1.2"/>')
        wy += 26
    # the front door at quay level
    dcol = rng.choice(['#2e5a3c', '#7a1f2b', '#1d3f5e'])
    parts.append(f'      <rect x="{cx - 5:.1f}" y="{QUAY - 20:.1f}" width="10" height="20" fill="{dcol}"/>')
    parts.append(f'      <rect x="{cx - 6.4:.1f}" y="{QUAY - 21.4:.1f}" width="12.8" height="2" fill="#ece4d2"/>')
    parts.append('    </g>')
    x += w + rng.uniform(1, 3)
    i += 1
parts.append('  </g>')
out.append('\n'.join(parts))

# ---- the quay: railing, bikes, tulips ----
out.append(f'''  <rect y="{QUAY}" width="{W}" height="{WATER - QUAY}" fill="#6a6058"/>
  <rect y="{QUAY}" width="{W}" height="3" fill="#7d7268"/>
  <line x1="0" y1="{QUAY + 9}" x2="{W}" y2="{QUAY + 9}" stroke="#2a2624" stroke-width="2"/>''')
posts = ['  <g stroke="#2a2624" stroke-width="2">']
for px in range(8, W, 28):
    posts.append(f'    <line x1="{px}" y1="{QUAY + 9}" x2="{px}" y2="{QUAY + 22}"/>')
posts.append('  </g>')
out.append('\n'.join(posts))


def bike(bx, by, flip=False):
    sc = -1 if flip else 1
    return f'''  <g stroke="#26221e" stroke-width="1.8" fill="none" transform="translate({bx} {by}) scale({sc} 1)">
    <circle cx="-9" cy="0" r="6.2"/>
    <circle cx="9" cy="0" r="6.2"/>
    <path d="M-9 0 L-3 -9 L6 -9 M-3 -9 L3 0 L-9 0 M3 0 L6 -9 M9 0 L6 -9"/>
    <path d="M-9 -9 L-3 -9 M-9 -9 L-11 -11"/>
    <line x1="-1" y1="-12" x2="1.5" y2="-12" stroke-width="2.4"/>
  </g>'''


def tulips(tx, ty, colors):
    stems, heads = [], []
    for k, c in enumerate(colors):
        sx = tx + k * 5 + rng.uniform(-1, 1)
        hh = ty - rng.uniform(9, 14)
        stems.append(f'    <line x1="{sx:.1f}" y1="{ty}" x2="{sx:.1f}" y2="{hh + 3:.1f}" stroke="#3e6a34" stroke-width="1.4"/>')
        heads.append(f'    <path d="M{sx - 2.6:.1f} {hh + 3:.1f} L{sx - 2.6:.1f} {hh:.1f} L{sx - 1:.1f} {hh + 1.6:.1f} L{sx:.1f} {hh:.1f} L{sx + 1:.1f} {hh + 1.6:.1f} L{sx + 2.6:.1f} {hh:.1f} L{sx + 2.6:.1f} {hh + 3:.1f} Q{sx:.1f} {hh + 5.5:.1f} {sx - 2.6:.1f} {hh + 3:.1f} Z" fill="{c}"/>')
    return '  <g>\n' + '\n'.join(stems + heads) + '\n  </g>'


out.append(bike(60, QUAY + 21))
out.append(bike(150, QUAY + 21, flip=True))
out.append(bike(262, QUAY + 21))
out.append(bike(352, QUAY + 21, flip=True))
out.append(tulips(96, QUAY + 22, ['#c8342a', '#e8c34a', '#d8689a', '#c8342a']))
out.append(tulips(198, QUAY + 22, ['#e8c34a', '#c8342a', '#e07a2a']))
out.append(tulips(304, QUAY + 22, ['#d8689a', '#c8342a', '#e8c34a', '#e07a2a']))

# ---- the canal ----
out.append(f'  <rect y="{WATER}" width="{W}" height="{H - WATER}" fill="url(#nlWater)"/>')

# facade reflections, broken by the water
refl = ['  <g filter="url(#nlSoft)" opacity="0.22">']
for fx, fw, brick in facades:
    depth = rng.uniform(34, 62)
    refl.append(f'    <rect x="{fx + 1.5:.1f}" y="{WATER + 2}" width="{fw - 3:.1f}" height="{depth:.1f}" fill="{brick}"/>')
refl.append('  </g>')
out.append('\n'.join(refl))
glints = ['  <g fill="#ece4d2" opacity="0.14" filter="url(#nlSoft)">']
for _ in range(9):
    gx = rng.uniform(10, 386)
    glints.append(f'    <rect x="{gx:.1f}" y="{WATER + rng.uniform(4, 30):.1f}" width="5" height="{rng.uniform(10, 22):.1f}"/>')
glints.append('  </g>')
out.append('\n'.join(glints))

out.append(f'''  <g fill="none" stroke="#3e5a4c" stroke-width="1.5" opacity="0.3">
    <path d="M0 {WATER + 52} Q100 {WATER + 48} 200 {WATER + 52} T400 {WATER + 52}"/>
    <path d="M0 {WATER + 92} Q100 {WATER + 88} 200 {WATER + 92} T400 {WATER + 92}"/>
    <path d="M0 {WATER + 126} Q100 {WATER + 122} 200 {WATER + 126} T400 {WATER + 126}"/>
  </g>

  <!-- houseboat moored on the near bank -->
  <g>
    <rect x="14" y="{WATER + 24}" width="104" height="20" rx="4" fill="#2e2a26"/>
    <rect x="30" y="{WATER + 10}" width="62" height="16" rx="3" fill="#4a5a48"/>
    <rect x="38" y="{WATER + 14}" width="9" height="7" rx="1.5" fill="#ffd98a" opacity="0.9"/>
    <rect x="56" y="{WATER + 14}" width="9" height="7" rx="1.5" fill="#ffd98a" opacity="0.9"/>
    <rect x="74" y="{WATER + 14}" width="9" height="7" rx="1.5" fill="#3a3630"/>
    <circle cx="24" cy="{WATER + 16}" r="4" fill="#2e5a3c"/>
    <rect x="22.5" y="{WATER + 19}" width="3" height="5" fill="#7a4430"/>
    <path d="M14 {WATER + 44} Q66 {WATER + 50} 118 {WATER + 44}" fill="none" stroke="#0e1714" stroke-width="2" opacity="0.6"/>
  </g>

  <!-- the rondvaart, gliding through (SMIL) -->
  <g>
    <animateTransform attributeName="transform" type="translate" values="440 {WATER + 66}; -110 {WATER + 72}" dur="55s" repeatCount="indefinite"/>
    <path d="M-38 6 Q-40 0 -34 -2 L34 -2 Q42 0 38 6 Q0 10 -38 6 Z" fill="#ece4d2"/>
    <path d="M-30 -2 L-26 -10 L28 -10 L31 -2 Z" fill="#8ab4c8" opacity="0.85"/>
    <g stroke="#5a7a8c" stroke-width="1">
      <line x1="-18" y1="-10" x2="-18" y2="-2"/>
      <line x1="-7" y1="-10" x2="-7" y2="-2"/>
      <line x1="4" y1="-10" x2="4" y2="-2"/>
      <line x1="15" y1="-10" x2="15" y2="-2"/>
    </g>
    <rect x="-34" y="-1" width="70" height="2.4" fill="#c8342a"/>
    <path d="M-48 8 Q0 12 48 8" fill="none" stroke="#0e1714" stroke-width="1.6" opacity="0.5"/>
  </g>
</svg>''')

open('public/frames/nl-amsterdam.svg', 'w').write('\n'.join(out) + '\n')
print('written public/frames/nl-amsterdam.svg')
