"""Generate public/frames/hr-adriatic.svg — the Croatia card background.

High summer on the Adriatic: a walled old town — round fortress tower,
crenellated white walls, a cascade of terracotta roofs, the campanile —
between the open sea with its islands and the dark harbor water below.
Gulls wheel and a sailboat passes (SMIL). Sky-critical content stays in
the y 190-245 band (cover-crop safe).
"""
import random

W, H = 400, 600
SEA_TOP = 244     # horizon
TOWN_TOP = 332    # where the roofs begin
WALL_TOP = 392    # the city wall's parapet
ROCKS = 472       # wall base meets the rocks
HARBOR = 508      # rocks meet the dark harbor water
rng = random.Random(23)

out = [f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- Adriatic summer for the Croatia card: the walled old town between
       two seas — open water with islands behind, dark harbor below. Gulls
       and a sailboat move via SMIL. Generated by scripts/build-croatia.py. -->
  <defs>
    <linearGradient id="hrSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2e6cb8" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#a8d0e8" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="hrSea" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#3a96bc"/>
      <stop offset="1" stop-color="#1d6a94"/>
    </linearGradient>
    <linearGradient id="hrHarbor" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#13293e"/>
      <stop offset="1" stop-color="#0a1a2c"/>
    </linearGradient>
  </defs>

  <rect width="{W}" height="{SEA_TOP}" fill="url(#hrSky)"/>
  <g fill="#f4f8fc" opacity="0.85">
    <ellipse cx="76" cy="204" rx="26" ry="7"/>
    <ellipse cx="96" cy="198" rx="16" ry="5"/>
    <ellipse cx="300" cy="222" rx="22" ry="6.5"/>
  </g>
  <!-- gulls -->
  <g stroke="#3a4a5c" stroke-width="1.6" fill="none" stroke-linecap="round">
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0; 30 8; 0 0" dur="19s" repeatCount="indefinite"/>
      <path d="M150 216 Q154 212 158 216 M154 214 Q158 210 162 214"/>
    </g>
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0; -24 -6; 0 0" dur="23s" repeatCount="indefinite"/>
      <path d="M236 230 Q240 226 244 230"/>
    </g>
  </g>

  <!-- islands hazy on the horizon -->
  <path d="M-8 {SEA_TOP} L36 {SEA_TOP - 10} L92 {SEA_TOP} Z" fill="#8aa8c0" opacity="0.8"/>
  <path d="M228 {SEA_TOP} L286 {SEA_TOP - 13} L352 {SEA_TOP} Z" fill="#8aa8c0" opacity="0.8"/>

  <!-- the open sea, glinting, a sailboat passing -->
  <rect y="{SEA_TOP}" width="{W}" height="{WALL_TOP + 8 - SEA_TOP}" fill="url(#hrSea)"/>
  <g fill="#ffffff">
    <ellipse cx="88" cy="{SEA_TOP + 18}" rx="4" ry="1.1" opacity="0"><animate attributeName="opacity" values="0;0.75;0" dur="2.7s" begin="0.3s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="212" cy="{SEA_TOP + 26}" rx="4.5" ry="1.2" opacity="0"><animate attributeName="opacity" values="0;0.7;0" dur="3.1s" begin="1.4s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="330" cy="{SEA_TOP + 20}" rx="4" ry="1.1" opacity="0"><animate attributeName="opacity" values="0;0.65;0" dur="2.5s" begin="0.8s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="150" cy="{SEA_TOP + 52}" rx="4" ry="1.1" opacity="0"><animate attributeName="opacity" values="0;0.6;0" dur="3.3s" begin="2.1s" repeatCount="indefinite"/></ellipse>
  </g>
  <g>
    <animateTransform attributeName="transform" type="translate" values="-40 {SEA_TOP + 42}; 440 {SEA_TOP + 36}" dur="58s" repeatCount="indefinite"/>
    <path d="M-11 4 L11 4 L6 9 L-6 9 Z" fill="#e8e4d8"/>
    <line x1="0" y1="4" x2="0" y2="-15" stroke="#d8d4c8" stroke-width="1"/>
    <path d="M1 -15 L1 2 L12 2 Z" fill="#ffffff"/>
    <path d="M-1 -12 L-1 2 L-10 2 Z" fill="#f0ede2"/>
  </g>
''']

# ---- towers first: the roofs will hide their feet ----
out.append(f'''  <!-- campanile and domed tower, rising from BEHIND the roofs -->
  <g>
    <rect x="296" y="{TOWN_TOP - 62}" width="22" height="{62 + 40}" fill="#ede4d2"/>
    <rect x="294" y="{TOWN_TOP - 66}" width="26" height="6" fill="#d8ccb4"/>
    <path d="M293 {TOWN_TOP - 66} L307 {TOWN_TOP - 88} L321 {TOWN_TOP - 66} Z" fill="#4a7580"/>
    <circle cx="307" cy="{TOWN_TOP - 90}" r="2" fill="#e8c34a"/>
    <g fill="#4a4438" opacity="0.85">
      <rect x="301" y="{TOWN_TOP - 56}" width="5" height="9" rx="2.4"/>
      <rect x="309" y="{TOWN_TOP - 56}" width="5" height="9" rx="2.4"/>
      <rect x="305" y="{TOWN_TOP - 38}" width="5" height="9" rx="2.4"/>
    </g>
  </g>
  <g>
    <rect x="161" y="{TOWN_TOP - 34}" width="22" height="60" fill="#e8dfc9"/>
    <rect x="159" y="{TOWN_TOP - 37}" width="26" height="4" fill="#d8ccb4"/>
    <path d="M158 {TOWN_TOP - 37} A14 12 0 0 1 186 {TOWN_TOP - 37} Z" fill="#4a7580"/>
    <circle cx="172" cy="{TOWN_TOP - 50}" r="1.8" fill="#e8c34a"/>
    <rect x="169" y="{TOWN_TOP - 28}" width="6" height="10" rx="2.6" fill="#4a4438" opacity="0.85"/>
  </g>

''')

# ---- the roofscape behind the wall ----
roofs = ['#c05a2e', '#d0703c', '#b04e28', '#c96434']
walls = ['#ede4d2', '#e2d8c2', '#f2ebd8']
rows = [(TOWN_TOP + 22, 11, 17, 20, 32, 1.0), (TOWN_TOP + 44, 13, 20, 24, 38, 1.0), (WALL_TOP + 4, 15, 22, 28, 42, 1.0)]
parts = ['  <g>']
for baseline, h_lo, h_hi, w_lo, w_hi, op in rows:
    row_parts = [f'    <g opacity="{op}">']
    x = rng.uniform(-10, -2)
    while x < W + 8:
        w = rng.uniform(w_lo, w_hi)
        h = rng.uniform(h_lo, h_hi)
        b = baseline + rng.uniform(-5, 5)
        roof = rng.choice(roofs)
        wall = rng.choice(walls)
        row_parts.append(f'      <rect x="{x:.1f}" y="{b:.1f}" width="{w:.1f}" height="40" fill="{wall}"/>')
        if rng.random() < 0.55:
            row_parts.append(f'      <path d="M{x - 1.5:.1f} {b:.1f} L{x + w / 2:.1f} {b - h:.1f} L{x + w + 1.5:.1f} {b:.1f} Z" fill="{roof}"/>')
        else:
            r = w * rng.uniform(0.24, 0.38)
            row_parts.append(f'      <path d="M{x - 1.5:.1f} {b:.1f} L{x + r:.1f} {b - h:.1f} L{x + w - r:.1f} {b - h:.1f} L{x + w + 1.5:.1f} {b:.1f} Z" fill="{roof}"/>')
        if rng.random() < 0.3:
            wx = x + w * rng.uniform(0.3, 0.6)
            row_parts.append(f'      <rect x="{wx:.1f}" y="{b + rng.uniform(5, 12):.1f}" width="3.5" height="6" rx="1.5" fill="#4a6a8a" opacity="0.8"/>')
        x += w
    row_parts.append('    </g>')
    parts.append('\n'.join(row_parts))
parts.append('  </g>')
out.append('\n'.join(parts))

out.append(f'''  <!-- the city wall: crenellated parapet and the round fortress tower -->
  <rect y="{WALL_TOP}" width="{W}" height="{ROCKS - WALL_TOP}" fill="#e8e0cc"/>
  <rect y="{WALL_TOP}" width="{W}" height="4" fill="#f2ebd8"/>''')
crenels = ['  <g fill="#e8e0cc">']
for cx in range(2, W, 18):
    crenels.append(f'    <rect x="{cx}" y="{WALL_TOP - 8}" width="10" height="8"/>')
crenels.append('  </g>')
out.append('\n'.join(crenels))
out.append(f'''  <g fill="none" stroke="#c9bda2" stroke-width="1.2" opacity="0.7">
    <line x1="0" y1="{WALL_TOP + 20}" x2="{W}" y2="{WALL_TOP + 20}"/>
    <line x1="0" y1="{WALL_TOP + 40}" x2="{W}" y2="{WALL_TOP + 40}"/>
    <line x1="0" y1="{WALL_TOP + 60}" x2="{W}" y2="{WALL_TOP + 60}"/>
  </g>
  <g fill="none" stroke="#d5c9ae" stroke-width="1" opacity="0.6">
    <line x1="130" y1="{WALL_TOP + 20}" x2="130" y2="{WALL_TOP + 40}"/>
    <line x1="168" y1="{WALL_TOP + 40}" x2="168" y2="{WALL_TOP + 60}"/>
    <line x1="252" y1="{WALL_TOP + 20}" x2="252" y2="{WALL_TOP + 40}"/>
    <line x1="290" y1="{WALL_TOP + 40}" x2="290" y2="{WALL_TOP + 60}"/>
    <line x1="352" y1="{WALL_TOP + 20}" x2="352" y2="{WALL_TOP + 40}"/>
  </g>
  <!-- the sea gate: arched, stone-ringed, with the grille half lowered -->
  <g>
    <path d="M188 {ROCKS} L188 {WALL_TOP + 34} A22 21 0 0 1 232 {WALL_TOP + 34} L232 {ROCKS} Z" fill="#d8ccb4"/>
    <path d="M192 {ROCKS} L192 {WALL_TOP + 37} A18 17 0 0 1 228 {WALL_TOP + 37} L228 {ROCKS} Z" fill="#3a332a"/>
    <g stroke="#5f5648" stroke-width="1.6">
      <line x1="198" y1="{WALL_TOP + 32}" x2="198" y2="{WALL_TOP + 52}"/>
      <line x1="205" y1="{WALL_TOP + 26}" x2="205" y2="{WALL_TOP + 52}"/>
      <line x1="212" y1="{WALL_TOP + 24}" x2="212" y2="{WALL_TOP + 52}"/>
      <line x1="219" y1="{WALL_TOP + 26}" x2="219" y2="{WALL_TOP + 52}"/>
      <line x1="226" y1="{WALL_TOP + 32}" x2="226" y2="{WALL_TOP + 52}"/>
      <line x1="194" y1="{WALL_TOP + 44}" x2="227" y2="{WALL_TOP + 44}"/>
    </g>
  </g>
  <g fill="#5a5044" opacity="0.7">
    <rect x="86" y="{WALL_TOP + 28}" width="7" height="12" rx="3"/>
    <rect x="148" y="{WALL_TOP + 32}" width="7" height="12" rx="3"/>
    <rect x="272" y="{WALL_TOP + 32}" width="7" height="12" rx="3"/>
    <rect x="334" y="{WALL_TOP + 28}" width="7" height="12" rx="3"/>
  </g>

  <!-- the round tower, Minčeta-style -->
  <g>
    <path d="M28 {ROCKS} L34 {TOWN_TOP - 6} Q62 {TOWN_TOP - 16} 90 {TOWN_TOP - 6} L96 {ROCKS} Z" fill="#ede4d2"/>
    <rect x="24" y="{TOWN_TOP - 22}" width="76" height="18" fill="#e2d8c2"/>
    <g fill="#e2d8c2">
      <rect x="26" y="{TOWN_TOP - 32}" width="11" height="10"/>
      <rect x="45" y="{TOWN_TOP - 32}" width="11" height="10"/>
      <rect x="64" y="{TOWN_TOP - 32}" width="11" height="10"/>
      <rect x="83" y="{TOWN_TOP - 32}" width="11" height="10"/>
    </g>
    <g fill="#5a5044" opacity="0.7">
      <rect x="44" y="{TOWN_TOP + 26}" width="6" height="10" rx="2.5"/>
      <rect x="72" y="{TOWN_TOP + 60}" width="6" height="10" rx="2.5"/>
    </g>
    <!-- the flag on the tower -->
    <line x1="62" y1="{TOWN_TOP - 32}" x2="62" y2="{TOWN_TOP - 50}" stroke="#5a4a3a" stroke-width="1.6"/>
    <g>
      <path d="M62 {TOWN_TOP - 50} L80 {TOWN_TOP - 47} L62 {TOWN_TOP - 44} Z" fill="#dd1c34"/>
      <animateTransform attributeName="transform" type="skewY" values="0;3;0;-3;0" dur="3.4s" repeatCount="indefinite" additive="sum"/>
    </g>
  </g>

  <!-- rocks at the wall's feet, then the dark harbor -->
  <path d="M0 {ROCKS} L400 {ROCKS} L400 {HARBOR + 14} Q300 {HARBOR + 4} 200 {HARBOR + 10} Q100 {HARBOR + 16} 0 {HARBOR + 6} Z" fill="#8a8272"/>
  <g fill="#6e675a">
    <path d="M30 {ROCKS + 12} L58 {ROCKS + 6} L74 {ROCKS + 20} L44 {ROCKS + 26} Z"/>
    <path d="M150 {ROCKS + 16} L180 {ROCKS + 10} L196 {ROCKS + 24} L162 {ROCKS + 28} Z"/>
    <path d="M290 {ROCKS + 10} L318 {ROCKS + 5} L334 {ROCKS + 18} L302 {ROCKS + 24} Z"/>
  </g>
  <rect y="{HARBOR + 10}" width="{W}" height="{H - HARBOR - 10}" fill="url(#hrHarbor)"/>
  <path d="M0 {HARBOR + 6} Q100 {HARBOR + 16} 200 {HARBOR + 10} Q300 {HARBOR + 4} 400 {HARBOR + 14} L400 {HARBOR + 26} Q300 {HARBOR + 16} 200 {HARBOR + 22} Q100 {HARBOR + 28} 0 {HARBOR + 18} Z" fill="#0f2236"/>
  <g fill="none" stroke="#2e4a64" stroke-width="1.5" opacity="0.3">
    <path d="M0 {HARBOR + 44} Q100 {HARBOR + 40} 200 {HARBOR + 44} T400 {HARBOR + 44}"/>
    <path d="M0 {HARBOR + 74} Q100 {HARBOR + 70} 200 {HARBOR + 74} T400 {HARBOR + 74}"/>
  </g>
</svg>''')

open('public/frames/hr-adriatic.svg', 'w').write('\n'.join(out) + '\n')
print('written public/frames/hr-adriatic.svg')
