import math, random

W, H = 400, 600
out = []

def fog_bank(y, lo, hi, seed, bottom=H + 10):
    """Cloud bank: a scalloped top edge made of upward arcs, so it reads as
    cumulus rather than a wavy line."""
    rng = random.Random(seed)
    x = -90.0
    d = [f"M{x:.0f} {bottom}", f"L{x:.0f} {y:.1f}"]
    while x < 490:
        r = rng.uniform(lo, hi)
        h = r * rng.uniform(0.5, 0.95)
        x2 = x + 2 * r
        d.append(f"A{r:.1f} {h:.1f} 0 0 1 {x2:.1f} {y:.1f}")
        x = x2
    d.append(f"L{x:.1f} {bottom} Z")
    return " ".join(d)

def poly(pts):
    return "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + " Z"

def chain_x(pts, apex_i, y, direction):
    """x on the silhouette at height y, walking the edges away from the apex —
    handles multi-segment slopes, so a cap can never overhang the outline."""
    idxs = range(apex_i, -1, -1) if direction < 0 else range(apex_i, len(pts))
    seq = [pts[i] for i in idxs]
    for (x1, y1), (x2, y2) in zip(seq, seq[1:]):
        if min(y1, y2) <= y <= max(y1, y2) and y2 != y1:
            return x1 + (x2 - x1) * (y - y1) / (y2 - y1)
    return seq[-1][0]

def cap(pts, apex_i, depth, dips=(0.24,)):
    """Lit summit cap. Its sides FOLLOW the silhouette, picking up every vertex
    down to the cap depth — a straight chord from the apex would cut inside a
    bent ridge and leave the rock showing on one side only."""
    ax, ay = pts[apex_i]
    y = ay + depth

    def walk(step):
        side, i = [], apex_i
        while 0 <= i + step < len(pts) and pts[i + step][1] < y:
            i += step
            side.append(pts[i])
        side.append((chain_x(pts, apex_i, y, step), y))
        return side

    right, left = walk(1), walk(-1)
    rx, lx = right[-1][0], left[-1][0]
    d = [f"M{ax:.1f} {ay:.1f}"]
    d += [f"L{x:.1f} {yy:.1f}" for x, yy in right]
    n = len(dips)
    for k, frac in enumerate(reversed(dips)):
        t = (k + 1) / (n + 1)
        d.append(f"L{rx + (lx - rx) * t:.1f} {y + depth * frac:.1f}")
    d += [f"L{x:.1f} {yy:.1f}" for x, yy in reversed(left)]
    d.append("Z")
    return " ".join(d)

# --- the Matterhorn: near-vertical north face left, long Hörnli ridge right ---
MT_RAW = [(138, 396), (176, 330), (192, 268), (208, 208), (226, 156), (243, 122),
          (250, 116), (258, 130), (268, 152), (288, 200), (312, 258), (344, 320),
          (378, 366), (400, 392), (400, 396)]
MT_APEX = 6
# scaled about the base centre: still clearly the dominant summit, but its tip
# now sits well below the card's country title
MT_SCALE = 0.70
MT_PTS = [(250 + (x - 250) * MT_SCALE, 396 - (396 - y) * MT_SCALE) for x, y in MT_RAW]
MT = poly(MT_PTS)
MT_CAP = cap(MT_PTS, MT_APEX, 38, dips=(0.10, 0.30, 0.16))

peaks = [
    # (vertices, apex index, cap depth, fill)
    ([(-10, 396), (26, 300), (58, 252), (92, 296), (120, 352), (138, 396)], 2, 20, "#232b4e"),
    ([(300, 396), (336, 306), (362, 258), (392, 312), (400, 342), (400, 396)], 2, 22, "#242c50"),
    ([(96, 396), (124, 330), (150, 296), (172, 340), (186, 396)], 2, 17, "#1e2646"),
]

out.append(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- full-card Swiss alpenglow for the Switzerland card: the Matterhorn's
       summit catching the first light while its base stays in cold shadow,
       seen from ABOVE the cloud line — the whole lower half is a drifting
       Nebelmeer. A balloon crosses on a slow loop. Deliberately unlike the
       Austria card: no snowfall, no valley, no cable car, dawn not dusk.
       Generated by scripts/build-alpenglow.py. -->
  <defs>
    <linearGradient id="chSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#131b3c" stop-opacity="0.97"/>
      <stop offset="0.3" stop-color="#33356a" stop-opacity="0.97"/>
      <stop offset="0.6" stop-color="#755d84" stop-opacity="0.97"/>
      <stop offset="0.84" stop-color="#c0748a" stop-opacity="0.97"/>
      <stop offset="1" stop-color="#eda478" stop-opacity="0.97"/>
    </linearGradient>
    <linearGradient id="chDeep" x1="0" y1="372" x2="0" y2="600" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#0d1330" stop-opacity="0"/>
      <stop offset="0.34" stop-color="#0d1330" stop-opacity="0.28"/>
      <stop offset="0.7" stop-color="#0b1029" stop-opacity="0.52"/>
      <stop offset="1" stop-color="#090d22" stop-opacity="0.66"/>
    </linearGradient>
    <filter id="chSoft" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="2.4"/>
    </filter>
    <filter id="chHaze" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="5"/>
    </filter>
    <clipPath id="chBalloon">
      <path d="M0 0 C-10.5 -2 -13 -11 -13 -18 C-13 -28.5 -7 -37 0 -37 C7 -37 13 -28.5 13 -18 C13 -11 10.5 -2 0 0 Z"/>
    </clipPath>
  </defs>

  <rect width="{W}" height="400" fill="url(#chSky)"/>

  <!-- the last stars, low in the west -->
  <g fill="#ffffff">
    <circle cx="46" cy="38" r="1.3" opacity="0.75"/>
    <circle cx="128" cy="26" r="1" opacity="0.6"/>
    <circle cx="196" cy="52" r="1.15" opacity="0.65"/>
    <circle cx="292" cy="34" r="1" opacity="0.55"/>
    <circle cx="352" cy="70" r="1.2" opacity="0.6"/>
    <circle cx="86" cy="96" r="1" opacity="0.45"/>
    <circle cx="238" cy="88" r="0.9" opacity="0.4"/>
  </g>
''')

out.append('  <!-- neighbouring summits, their tips already lit -->')
for pts, apex_i, depth, fill in peaks:
    out.append(f'  <path d="{poly(pts)}" fill="{fill}"/>')
out.append('  <g fill="#f0a173" opacity="0.75">')
for pts, apex_i, depth, fill in peaks:
    out.append(f'    <path d="{cap(pts, apex_i, depth)}"/>')
out.append('  </g>')

out.append(f'''
  <!-- the Matterhorn: drawn exactly like its neighbours, just taller -->
  <path d="{MT}" fill="#28324f"/>
  <path d="{MT_CAP}" fill="#f0a173" opacity="0.78"/>

  <!-- balloon drifting across on a slow loop (Château-d'Œx) -->
  <g>
    <animateTransform attributeName="transform" type="translate"
      values="446 0; -46 0" dur="78s" repeatCount="indefinite"/>
    <g transform="translate(0 292)">
      <g clip-path="url(#chBalloon)">
        <rect x="-14" y="-38" width="28" height="39" fill="#d8232a"/>
        <ellipse cx="-7" cy="-19" rx="3.1" ry="19" fill="#f4f1ea"/>
        <ellipse cx="7" cy="-19" rx="3.1" ry="19" fill="#f4f1ea"/>
        <ellipse cx="0" cy="-19" rx="1.5" ry="19" fill="#b0161c" opacity="0.5"/>
      </g>
      <path d="M-4 0 L-2.6 4.2 M4 0 L2.6 4.2" stroke="#6a5236" stroke-width="0.8"/>
      <rect x="-3.4" y="4" width="6.8" height="4.4" rx="1" fill="#8a6a42"/>
    </g>
  </g>
''')

# --- the Nebelmeer: banks from far/lit to near/shadowed ---
banks = [
    # y, scallop lo/hi, seed, lit crest, shadowed body, gradient span, opacity, filter
    (356, 9, 17, 101, '#dc9a8a', '#5c5578', 58, 0.9, 'url(#chHaze)'),
    (392, 11, 21, 202, '#b8808c', '#474769', 56, 0.94, 'url(#chSoft)'),
    (446, 14, 26, 303, '#8a7290', '#33345a', 50, 0.97, None),
    (502, 18, 32, 404, '#5d5878', '#22264a', 48, 1.0, None),
    (556, 22, 38, 505, '#40406a', '#191d3a', 46, 1.0, None),
]
drifts = [(-26, 62), (22, 74), (-18, 88), (14, 96), (-11, 108)]

out.append('  <!-- the Nebelmeer filling the valley, drifting in layers -->')
out.append('  <defs>')
for i, (y, lo, hi, seed, ctop, cbot, span, op, filt) in enumerate(banks):
    out.append(f'''    <linearGradient id="chFog{i}" x1="0" y1="{y}" x2="0" y2="{y + span}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="{ctop}"/>
      <stop offset="1" stop-color="{cbot}"/>
    </linearGradient>''')
out.append('  </defs>')

for i, (y, lo, hi, seed, ctop, cbot, span, op, filt) in enumerate(banks):
    dx, dur = drifts[i]
    f = f' filter="{filt}"' if filt else ''
    out.append(f'''  <g{f}>
    <animateTransform attributeName="transform" type="translate"
      values="0 0; {dx} 0; 0 0" dur="{dur}s" repeatCount="indefinite"/>
    <path d="{fog_bank(y, lo, hi, seed)}" fill="url(#chFog{i})" opacity="{op}"/>
  </g>''')

# --- foreground: the ledge we stand on, with a cairn ---
out.append(f'''
  <rect y="372" width="{W}" height="{H - 372}" fill="url(#chDeep)"/>

  <path d="M-6 {H} L-6 572 Q60 560 130 570 Q210 580 290 568 Q350 560 406 572 L406 {H} Z" fill="#131a2c"/>
</svg>''')

open('/Users/milanalbertz/Desktop/Projects/MilanAlbertzWebsite/public/frames/ch-alpenglow.svg', 'w').write("\n".join(out) + "\n")
print('written')
