"""Generate the two Spain backgrounds:

  es-mediterranean.svg — Alicante gold: the Castell de Santa Bárbara on its
                         crag, seafront facades, palms, the Explanada's
                         tri-colour wave, a sailboat on the turquoise sea
  es-canarias.svg      — volcanic dusk for the Canary places: Teide on the
                         horizon, rust fire-mountains, white Manrique cube
                         houses with green doors on black lava, embers rising

Country default + Alicante + Mallorca show the Mediterranean; the four
Canary islands crossfade to the volcanic scene. Sky-critical content stays
in the y 190-245 band (the card cover-crops the top ~185 units).
"""
import random

W, H = 400, 600


# ---------------------------------------------------------- Mediterranean
def mediterranean():
    rng = random.Random(42)

    # seafront facades between the palms and the castle crag
    facades = ['  <g>']
    palette = ['#e8d8b8', '#d8b894', '#e0c4a0', '#cfa06e', '#e6cfae']
    x = -6
    while x < 244:
        w = rng.uniform(30, 46)
        h = rng.uniform(58, 88)
        c = rng.choice(palette)
        top = 395 - h
        facades.append(f'    <rect x="{x:.1f}" y="{top:.1f}" width="{w:.1f}" height="{h:.1f}" fill="{c}"/>')
        facades.append(f'    <rect x="{x:.1f}" y="{top:.1f}" width="{w:.1f}" height="4" fill="#a05a3a"/>')
        wy = top + 12
        while wy < 380:
            wx = x + 5
            while wx < x + w - 7:
                facades.append(f'    <rect x="{wx:.1f}" y="{wy:.1f}" width="5" height="8" rx="1" fill="#4a3a30" opacity="0.7"/>')
                if rng.random() < 0.45:  # little balcony rail
                    facades.append(f'    <rect x="{wx - 1.2:.1f}" y="{wy + 8:.1f}" width="7.4" height="1.6" fill="#2a2624" opacity="0.8"/>')
                wx += 11
            wy += 17
        x += w
    facades.append('  </g>')
    facades_svg = '\n'.join(facades)

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- Alicante gold for the Spain card: Santa Bárbara castle on its crag,
       seafront facades and palms over the Explanada's tri-colour wave, and
       the turquoise Mediterranean below — a sailboat crosses, gulls wheel
       (SMIL). Generated by scripts/build-spain.py. -->
  <defs>
    <linearGradient id="emSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2e6cb8" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#9fd0e8" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="emSea" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2e8ab0"/>
      <stop offset="0.55" stop-color="#1a5a80"/>
      <stop offset="1" stop-color="#0e3550"/>
    </linearGradient>
  </defs>

  <rect width="{W}" height="425" fill="url(#emSky)"/>
  <g fill="#f4f8fc" opacity="0.85">
    <ellipse cx="60" cy="206" rx="28" ry="7.5"/>
    <ellipse cx="82" cy="199" rx="17" ry="5.5"/>
    <ellipse cx="170" cy="226" rx="22" ry="6.5"/>
  </g>
  <!-- gulls wheeling over the bay -->
  <g stroke="#3a4a5c" stroke-width="1.6" fill="none" stroke-linecap="round">
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0; -34 10; 0 0" dur="17s" repeatCount="indefinite"/>
      <path d="M120 218 Q124 214 128 218 M124 216 Q128 212 132 216"/>
    </g>
    <g>
      <animateTransform attributeName="transform" type="translate" values="0 0; 26 -7; 0 0" dur="21s" repeatCount="indefinite"/>
      <path d="M204 236 Q208 232 212 236"/>
    </g>
  </g>

  <!-- the castle crag: Santa Bárbara over the sea -->
  <g>
    <path d="M232 425 L244 330 L268 292 L306 270 L352 262 L400 270 L400 425 Z" fill="#8a6d4a"/>
    <path d="M262 425 L272 330 L306 296 L352 288 L400 296 L400 425 Z" fill="#a1815a" opacity="0.55"/>
    <!-- keep, walls and towers -->
    <rect x="292" y="240" width="76" height="48" fill="#b39268"/>
    <g fill="#a1815a">
      <rect x="292" y="240" width="76" height="5"/>
      <rect x="296" y="235" width="7" height="6"/>
      <rect x="310" y="235" width="7" height="6"/>
      <rect x="324" y="235" width="7" height="6"/>
      <rect x="338" y="235" width="7" height="6"/>
      <rect x="352" y="235" width="7" height="6"/>
    </g>
    <rect x="282" y="222" width="22" height="70" fill="#b39268"/>
    <rect x="280" y="216" width="26" height="7" fill="#8a6d4a"/>
    <rect x="344" y="228" width="18" height="62" fill="#ab8a60"/>
    <rect x="342" y="222" width="22" height="7" fill="#8a6d4a"/>
    <g fill="#4a3a30" opacity="0.7">
      <rect x="290" y="234" width="4" height="7" rx="1.5"/>
      <rect x="350" y="240" width="4" height="7" rx="1.5"/>
      <rect x="316" y="252" width="4" height="7" rx="1.5"/>
      <rect x="334" y="252" width="4" height="7" rx="1.5"/>
    </g>
    <!-- the flag on the keep -->
    <line x1="293" y1="216" x2="293" y2="204" stroke="#5a4a3a" stroke-width="1.4"/>
    <path d="M293 204 L305 206.5 L293 209 Z" fill="#c8342a"/>
  </g>

{facades_svg}

  <!-- palms along the esplanade -->
  <g>
    <g fill="none" stroke="#6a4a2a" stroke-width="4">
      <path d="M46 395 C48 372 42 352 48 334"/>
      <path d="M136 395 C134 376 140 360 134 344"/>
      <path d="M212 395 C214 378 208 364 214 350"/>
    </g>
    <g fill="#3e6a44">
      <path d="M48 334 C34 325 20 325 11 332 C24 319 42 321 48 328 C55 319 72 318 84 326 C72 322 57 325 48 334 Z"/>
      <path d="M48 334 C38 341 30 348 27 357 C31 345 39 338 48 339 C57 338 65 345 69 356 C67 346 58 340 48 334 Z"/>
      <path d="M134 344 C122 336 110 336 102 342 C113 331 129 333 134 339 C140 331 155 330 165 337 C155 334 142 336 134 344 Z"/>
      <path d="M134 344 C126 350 119 356 117 364 C120 353 127 347 134 348 C141 347 148 353 151 363 C149 354 141 349 134 344 Z"/>
      <path d="M214 350 C204 343 193 343 186 348 C196 338 210 340 214 346 C219 338 232 337 241 343 C232 341 221 343 214 350 Z"/>
      <path d="M214 350 C207 355 201 360 199 367 C202 358 208 352 214 353 C220 352 226 357 229 366 C227 358 220 354 214 350 Z"/>
    </g>
  </g>

  <!-- the Explanada: red, cream and black marble waves -->
  <rect y="395" width="{W}" height="30" fill="#e8dcc0"/>
  <g fill="none" stroke-width="9">
    <path d="M-12 403 Q12 396 36 403 T84 403 T132 403 T180 403 T228 403 T276 403 T324 403 T372 403 T420 403" stroke="#a33b2e"/>
    <path d="M-12 417 Q12 410 36 417 T84 417 T132 417 T180 417 T228 417 T276 417 T324 417 T372 417 T420 417" stroke="#2a2624"/>
  </g>

  <!-- the Mediterranean -->
  <rect y="425" width="{W}" height="{H - 425}" fill="url(#emSea)"/>
  <g fill="#ffffff">
    <ellipse cx="86" cy="446" rx="4" ry="1.1" opacity="0"><animate attributeName="opacity" values="0;0.7;0" dur="2.8s" begin="0.4s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="212" cy="452" rx="4.5" ry="1.2" opacity="0"><animate attributeName="opacity" values="0;0.75;0" dur="2.5s" begin="1.5s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="330" cy="448" rx="4" ry="1.1" opacity="0"><animate attributeName="opacity" values="0;0.65;0" dur="3.1s" begin="0.9s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="150" cy="486" rx="4" ry="1.1" opacity="0"><animate attributeName="opacity" values="0;0.6;0" dur="2.9s" begin="2s" repeatCount="indefinite"/></ellipse>
    <ellipse cx="280" cy="494" rx="3.5" ry="1" opacity="0"><animate attributeName="opacity" values="0;0.6;0" dur="3.3s" begin="0.2s" repeatCount="indefinite"/></ellipse>
  </g>
  <g fill="none" stroke="#7ac0d8" stroke-width="1.5" opacity="0.22">
    <path d="M0 468 Q100 464 200 468 T400 468"/>
    <path d="M0 516 Q100 512 200 516 T400 516"/>
    <path d="M0 562 Q100 558 200 562 T400 562"/>
  </g>

  <!-- a lateen sailboat working the bay -->
  <g>
    <animateTransform attributeName="transform" type="translate" values="440 476; -50 484" dur="60s" repeatCount="indefinite"/>
    <path d="M-13 4 Q0 9 13 4 L9 0 L-10 0 Z" fill="#e8dcc0"/>
    <line x1="0" y1="0" x2="0" y2="-17" stroke="#8a6d4a" stroke-width="1.2"/>
    <path d="M-1 -17 C-8 -10 -11 -4 -12 1 L-1 1 Z" fill="#f4efe0"/>
    <path d="M1 -13 L1 1 L9 1 Z" fill="#e8ddc4"/>
  </g>
</svg>'''


# --------------------------------------------------------------- Canarias
def canarias():
    rng = random.Random(7)

    # white Manrique cubes scattered over the ash at two depths — a hazier
    # back rank and a bolder front rank, with real gaps between houses
    def cube_rank(baseline, scale, gap_lo, gap_hi, seed):
        r = random.Random(seed)
        parts = []
        x = r.uniform(-8, 20)
        while x < W + 6:
            w = r.uniform(30, 48) * scale
            hh = r.uniform(26, 40) * scale
            top = baseline - hh
            parts.append(f'    <rect x="{x:.1f}" y="{top:.1f}" width="{w:.1f}" height="{hh:.1f}" fill="#f2efe6"/>')
            parts.append(f'    <rect x="{x + 1:.1f}" y="{top:.1f}" width="{w - 2:.1f}" height="2.4" fill="#dcd8ca"/>')
            if r.random() < 0.75:  # green door
                dx = x + w * r.uniform(0.3, 0.55)
                dh = 13 * scale
                parts.append(f'    <rect x="{dx:.1f}" y="{baseline - dh:.1f}" width="{7 * scale:.1f}" height="{dh:.1f}" fill="#2e7a3c"/>')
            wx = x + 5 * scale
            while wx < x + w - 9 * scale:
                if r.random() < 0.6:
                    parts.append(f'    <rect x="{wx:.1f}" y="{top + 8 * scale:.1f}" width="{6 * scale:.1f}" height="{7 * scale:.1f}" fill="#2e7a3c" opacity="0.9"/>')
                    parts.append(f'    <rect x="{wx - 1:.1f}" y="{top + 6.8 * scale:.1f}" width="{8 * scale:.1f}" height="1.4" fill="#2e7a3c"/>')
                wx += 13 * scale
            x += w + r.uniform(gap_lo, gap_hi)
        return parts

    cubes = ['  <g opacity="0.88">'] + cube_rank(452, 0.76, 16, 44, 71) + ['  </g>']
    cubes += ['  <g>'] + cube_rank(497, 1.0, 22, 58, 72) + ['  </g>']
    cubes_svg = '\n'.join(cubes)

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">
  <!-- volcanic dusk for Spain's Canary places: Teide on the horizon, rust
       fire-mountains, white cube houses with green doors on black lava,
       embers drifting up from the ground (SMIL).
       Generated by scripts/build-spain.py. -->
  <defs>
    <linearGradient id="ecSky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#3a2a55" stop-opacity="0.96"/>
      <stop offset="0.55" stop-color="#c85a3e" stop-opacity="0.96"/>
      <stop offset="1" stop-color="#e8935a" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="ecLava" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a1512"/>
      <stop offset="1" stop-color="#0d0a08"/>
    </linearGradient>
  </defs>

  <rect width="{W}" height="430" fill="url(#ecSky)"/>
  <g fill="#ffffff">
    <circle cx="70" cy="196" r="1.1" opacity="0.6"/>
    <circle cx="196" cy="190" r="1" opacity="0.5"/>
    <circle cx="330" cy="200" r="1.1" opacity="0.55">
      <animate attributeName="opacity" values="0.25;0.7;0.25" dur="3.8s" repeatCount="indefinite"/>
    </circle>
  </g>

  <!-- Teide: a cratered cone, smoking; haze sits BEHIND it and its base
       runs down behind the ridge so it stands grounded -->
  <rect x="-10" y="376" width="420" height="16" fill="#e8935a" opacity="0.14"/>
  <path d="M100 448 L180 244 L187 233 L196 237 L205 233 L212 244 L290 448 Z" fill="#584268" opacity="0.92"/>
  <path d="M187 233 L196 237 L205 233 L200 240 L192 240 Z" fill="#3e2c4a" opacity="0.9"/>
  <g fill="#cfc4d4">
    <circle cx="196" cy="228" r="3" opacity="0">
      <animate attributeName="cy" values="230;204" dur="5s" begin="0s" repeatCount="indefinite"/>
      <animate attributeName="r" values="2.5;7.5" dur="5s" begin="0s" repeatCount="indefinite"/>
      <animate attributeName="opacity" values="0.5;0" dur="5s" begin="0s" repeatCount="indefinite"/>
    </circle>
    <circle cx="199" cy="228" r="3" opacity="0">
      <animate attributeName="cy" values="230;206" dur="5s" begin="1.7s" repeatCount="indefinite"/>
      <animate attributeName="r" values="2.5;7" dur="5s" begin="1.7s" repeatCount="indefinite"/>
      <animate attributeName="opacity" values="0.45;0" dur="5s" begin="1.7s" repeatCount="indefinite"/>
    </circle>
    <circle cx="193" cy="228" r="3" opacity="0">
      <animate attributeName="cy" values="230;205" dur="5s" begin="3.4s" repeatCount="indefinite"/>
      <animate attributeName="r" values="2.5;7" dur="5s" begin="3.4s" repeatCount="indefinite"/>
      <animate attributeName="opacity" values="0.45;0" dur="5s" begin="3.4s" repeatCount="indefinite"/>
    </circle>
  </g>

  <!-- the fire mountains: notched cinder cones with scree gullies -->
  <g>
    <path d="M-24 430 L30 348 L42 354 L56 344 L128 430 Z" fill="#7a3a28"/>
    <path d="M30 348 L42 354 L56 344 L46 340 Z" fill="#4a2014"/>
    <g stroke="#5a2a1c" stroke-width="2" fill="none" opacity="0.8">
      <path d="M36 356 L18 404"/>
      <path d="M48 358 L54 408"/>
      <path d="M58 352 L86 412"/>
    </g>
  </g>
  <g>
    <path d="M222 430 L294 352 L306 358 L322 346 L412 430 Z" fill="#8f4530"/>
    <path d="M294 352 L306 358 L322 346 L310 342 Z" fill="#5a2a1c"/>
    <g stroke="#6a3020" stroke-width="2" fill="none" opacity="0.8">
      <path d="M296 362 L272 414"/>
      <path d="M310 362 L318 416"/>
      <path d="M324 354 L356 414"/>
    </g>
  </g>
  <path d="M124 430 L196 392 L226 396 L312 430 Z" fill="#63301f"/>

  <!-- the lava field -->
  <rect y="430" width="{W}" height="{H - 430}" fill="url(#ecLava)"/>
  <!-- ash apron the village stands on -->
  <path d="M0 452 L400 444 L400 503 L0 509 Z" fill="#2a1d12"/>
  <!-- angular fissures and rubble: rock, not ripples -->
  <g fill="none" stroke="#38291f" stroke-width="2" opacity="0.85">
    <path d="M24 496 L52 490 L66 498 L92 492"/>
    <path d="M148 524 L172 516 L184 526 L214 518"/>
    <path d="M286 488 L312 494 L330 486 L360 492"/>
    <path d="M66 560 L96 552 L112 562 L142 554"/>
    <path d="M252 570 L282 562 L296 572 L328 564"/>
  </g>
  <g fill="#241c16">
    <path d="M40 518 L52 512 L60 520 L48 526 Z"/>
    <path d="M198 548 L212 542 L220 552 L206 556 Z"/>
    <path d="M330 528 L342 522 L350 532 L338 536 Z"/>
    <path d="M120 584 L134 578 L142 588 L128 592 Z"/>
  </g>
  <g fill="#3a2c22">
    <path d="M44 516 L52 512 L56 517 Z"/>
    <path d="M202 546 L212 542 L216 548 Z"/>
    <path d="M334 526 L342 522 L346 528 Z"/>
  </g>

{cubes_svg}

  <!-- a lone dragon tree planted in the foreground lava -->
  <g>
    <ellipse cx="376" cy="530" rx="18" ry="3.5" fill="#000000" opacity="0.35"/>
    <path d="M374 530 C376 512 370 496 376 482" fill="none" stroke="#3a2a20" stroke-width="5.5"/>
    <g fill="#2e5a34">
      <ellipse cx="377" cy="478" rx="22" ry="7"/>
      <ellipse cx="363" cy="486" rx="13" ry="4.5"/>
      <ellipse cx="392" cy="487" rx="12" ry="4.5"/>
    </g>
  </g>

  <!-- embers drifting up off the lava -->
  <g fill="#ff9a3a">
    <circle cx="70" cy="520" r="1.8" opacity="0">
      <animate attributeName="opacity" values="0;0.85;0" dur="4.2s" begin="0.5s" repeatCount="indefinite"/>
      <animate attributeName="cy" values="530;486" dur="4.2s" begin="0.5s" repeatCount="indefinite"/>
    </circle>
    <circle cx="180" cy="548" r="1.5" opacity="0">
      <animate attributeName="opacity" values="0;0.7;0" dur="5s" begin="2.1s" repeatCount="indefinite"/>
      <animate attributeName="cy" values="556;512" dur="5s" begin="2.1s" repeatCount="indefinite"/>
    </circle>
    <circle cx="262" cy="512" r="1.6" opacity="0">
      <animate attributeName="opacity" values="0;0.8;0" dur="4.6s" begin="1.2s" repeatCount="indefinite"/>
      <animate attributeName="cy" values="522;480" dur="4.6s" begin="1.2s" repeatCount="indefinite"/>
    </circle>
    <circle cx="338" cy="556" r="1.5" opacity="0">
      <animate attributeName="opacity" values="0;0.7;0" dur="5.4s" begin="3.4s" repeatCount="indefinite"/>
      <animate attributeName="cy" values="564;520" dur="5.4s" begin="3.4s" repeatCount="indefinite"/>
    </circle>
  </g>
</svg>'''


for name, fn in [('es-mediterranean', mediterranean), ('es-canarias', canarias)]:
    path = f'public/frames/{name}.svg'
    open(path, 'w').write(fn() + '\n')
    print('written', path)
